# https://github.com/MoJo2600/pihole-kubernetes/blob/master/charts/pihole/values.yaml
# https://github.com/MoJo2600/pihole-kubernetes/issues/184

virtualHost: solo.lab

# -- Configuration for the DNS service on port 53
serviceDns:

  # -- `spec.type` for the DNS Service
  type: LoadBalancer

  # -- A fixed `spec.loadBalancerIP` for the DNS Service
  loadBalancerIP: "192.168.255.11"

# -- Configuration for the DHCP service on port 67
serviceDhcp:

  # -- `spec.type` for the DHCP Service
  type: LoadBalancer

  # -- A fixed `spec.loadBalancerIP` for the DHCP Service
  loadBalancerIP: "192.168.255.11"


# -- Configuration for the Ingress
ingress:
  # -- Generate a Ingress resource
  enabled: true

  # -- Annotations for the ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: issuer-ca
    # https://www.ziji.work/ingress/traefik-route-traefik-middlewares-configure.html
    # 指定使用的 Middleware，规则是 {namespace名称}-{middleware名称}@{资源类型}，如果使用多个中间件，则逗号隔开
    traefik.ingress.kubernetes.io/router.middlewares: traefik-subpath-stripprefixregex@kubernetescrd
  path: /sub-pihole/
  hosts:
    # virtualHost (default value is pi.hole) will be appended to the hosts
    - solo.lab
  tls:
    - secretName: solo.lab
      hosts:
        - solo.lab

# -- `spec.PersitentVolumeClaim` configuration
persistentVolumeClaim:
  # -- set to true to use pvc
  enabled: true

# -- default upstream DNS 1 server to use
DNS1: "192.168.255.1"
# -- default upstream DNS 2 server to use
DNS2: "223.5.5.5"

# -- should container run in privileged mode
privileged: "true"

podDnsConfig:
  enabled: false