apiVersion: v1
kind: Pod
metadata:
  name: lam
  labels:
    name: lam
spec:
  # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html
  # https://github.com/containers/podman/issues/7626
  containers:
    # https://github.com/LDAPAccountManager/lam/tree/develop/lam-packaging/docker
    - name: lam
      image: docker.io/ldapaccountmanager/lam:8.2
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: TZ
          value: Asia/Shanghai
      envFrom:
        - configMapRef:
            name: lam_env
      ports:
        - name: lam
          containerPort: 80
          hostPort: 8080
      volumeMounts:
        # https://github.com/LDAPAccountManager/lam/blob/develop/lam-packaging/docker/start.sh
        - name: lam_var_config
          mountPath: /var/lib/ldap-account-manager/config/lam.conf
        - name: lam_etc_config
          mountPath: /etc/ldap-account-manager/config.cfg

  volumes:
    - name: lam_var_config
      hostPath:
        path: /home/vagrant/infra/openldap/lam_config/lam.conf
        type: File
    - name: lam_etc_config
      hostPath:
        path: /home/vagrant/infra/openldap/lam_config/config.cfg
        type: File

  restartPolicy: OnFailure