apiVersion: v1
kind: Pod
metadata:
  name: openldap
  labels:
    name: openldap
spec:
  # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html
  # https://github.com/containers/podman/issues/7626
  containers:
    - name: openldap
      image: docker.io/bitnami/openldap:2.6.3-debian-11-r55
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      # https://github.com/bitnami/containers/issues/1475
      securityContext:
        runAsUser: 1000
      env:
        - name: TZ
          value: Asia/Shanghai
      envFrom:
        - configMapRef:
            name: openldap_env
      ports:
        - name: ldap
          containerPort: 1389
          hostPort: 389
        - name: ldaps
          containerPort: 1636
          hostPort: 636
      volumeMounts:
        - name: openldap_data
          mountPath: /bitnami/openldap/
        # https://github.com/bitnami/containers/tree/main/bitnami/openldap#configuration
        # https://github.com/d7z-project/all-in-kubernetes/blob/1a50dccca86c8c3bf8128891267af3b9a75e4211/system-app-deploy/openldap/conf/05-ldap-app.yaml
        - name: openldap_schema
          # mountPath: /opt/bitnami/openldap/etc/schema/memberof.ldif
          mountPath: /schema/
        - name: openldap_bootstrap
          mountPath: /ldifs/
        - name: openldap_cert
          mountPath: /opt/bitnami/openldap/certs/
    # # https://github.com/LDAPAccountManager/lam/tree/develop/lam-packaging/docker
    - name: lum
      image: docker.io/wheelybird/ldap-user-manager:v1.10
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        - name: TZ
          value: Asia/Shanghai
      envFrom:
        - configMapRef:
            name: lum_env
      ports:
        - name: http
          containerPort: 80
          hostPort: 8080
        - name: https
          containerPort: 443
          hostPort: 8443

  volumes:
    - name: openldap_data
      hostPath:
        path: /home/vagrant/infra/openldap/data
        type: Directory
    - name: openldap_schema
      configMap:
        name: openldap_ldif
        items:
          - key: memberof.ldif
            # https://github.com/bitnami/containers/tree/main/bitnami/openldap#configuration:~:text=files.%20Default%3A%20no-,LDAP_CUSTOM_LDIF_DIR,-%3A%20Location%20of%20a
            path: custom.ldif
    - name: openldap_bootstrap
      configMap:
        name: openldap_ldif
        items:
          - key: 01-top.ldif
            path: 01-top.ldif
          # - key: 02-users-admin.ldif
          #   path: 02-users-admin.ldif
          # - key: 03-cluster-groups.ldif
          #   path: 03-cluster-groups.ldif
    - name: openldap_cert
      hostPath: 
        path: /home/vagrant/infra/openldap/certs
        type: Directory

  restartPolicy: OnFailure