# code: language=ansible
---
# tasks file for ansible-podman-rootless
- name: "{{ package.podman.state }} Podman Package"
  when: package.podman.state != "skipped"
  ansible.builtin.include_tasks:
    file: Set-PodmanPackage.yml

- name: Detect podman package
  ansible.builtin.package_facts:
    manager: auto


# https://github.com/containers/podman/blob/main/troubleshooting.md#26-running-containers-with-resource-limits-fails-with-a-permissions-error
- name: Set cgroup resource permission to unprivileged user
  when:
    - not (
      ('podman' in ansible_facts.packages) 
      and (cgroups_delegation.state == "skipped") 
      )
  vars:
    # https://serverfault.com/questions/907164/ansible-conditionally-define-variables-in-vars-file-if-a-certain-condition-is-m
    switch_cgroups_delegation: "{% if not 'podman' in ansible_facts.packages %}absent{% else %}{{ cgroups_delegation.state }}{% endif %}"
    definitive_cgroups_delegation: "{{ lookup('vars','case_cgroups_delegate_' + switch_cgroups_delegation) }}"
  ansible.builtin.include_tasks:
    file: Set-CgroupConfig.yml
  register: Grant_ResourcePermission

# https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md#enable-unprivileged-ping
- name: Set Sysctl control permission to unprivileged user
  when:
    - not (
      ('podman' in ansible_facts.packages) 
        and (sysctl_params.state == "skipped") 
      )
  vars:
    # https://serverfault.com/questions/907164/ansible-conditionally-define-variables-in-vars-file-if-a-certain-condition-is-m
    switch_sysctl_params: "{% if not 'podman' in ansible_facts.packages %}absent{% else %}{{ sysctl_params.state }}{% endif %}"
    definitive_sysctl_params: "{{ lookup('vars','case_sysctl_params_' + switch_sysctl_params) }}"
  ansible.builtin.include_tasks:
    file: Set-SysctlParams.yml

# https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md#etcsubuid-and-etcsubgid-configuration
- name: Set subgid & subuid
  when:
    - not (
      ('podman' in ansible_facts.packages) 
      and (sub_ids.state == "skipped") 
      )
  vars:
    # https://serverfault.com/questions/907164/ansible-conditionally-define-variables-in-vars-file-if-a-certain-condition-is-m
    switch_sub_ids: "{% if not 'podman' in ansible_facts.packages %}absent{% else %}{{ sub_ids.state }}{% endif %}"
    definitive_sub_ids: "{{ lookup('vars','case_sub_ids_' + switch_sub_ids) }}"
  ansible.builtin.include_tasks:
    file: Set-SubIDs.yml
  # when:
  #   - ansible_facts['os_family'] == 'Alpine'

- name: Set kernel modules for podman
  when:
    - not (
      ('podman' in ansible_facts.packages) 
      and (kernel_modules.state == "skipped") 
      )
  vars:
    # https://serverfault.com/questions/907164/ansible-conditionally-define-variables-in-vars-file-if-a-certain-condition-is-m
    switch_kernel_modules: "{% if not 'podman' in ansible_facts.packages %}absent{% else %}{{ kernel_modules.state }}{% endif %}"
    definitive_kernel_modules: "{{ lookup('vars','case_kernel_modules_' + switch_kernel_modules) }}"
  ansible.builtin.include_tasks:
    file: Set-KernelModules.yml

- name: Set podman socket service
  when:
    - not (
      ('podman' in ansible_facts.packages) 
      and (service.podman_socket.user_scope == "skipped") 
      and (service.podman_socket.system_scope == "skipped")
      )
  vars:
    # https://serverfault.com/questions/907164/ansible-conditionally-define-variables-in-vars-file-if-a-certain-condition-is-m
    service_podman_user_socket_definitive: "{% if not 'podman' in ansible_facts.packages %}absent{% else %}{{ service.podman_socket.user_scope }}{% endif %}"
    service_podman_system_socket_definitive: "{% if not 'podman' in ansible_facts.packages %}absent{% else %}{{ service.podman_socket.system_scope }}{% endif %}"
    service_podman_user: "{{ lookup('vars','case_service_podman_user_socket_' + service_podman_user_socket_definitive) }}"
    service_podman_system: "{{ lookup('vars','case_service_podman_system_socket_' + service_podman_system_socket_definitive) }}"
  ansible.builtin.include_tasks:
    file: Set-PodmanSocketService.yml
  register: Enable_PodmanSocket
  