apiVersion: v1
kind: ConfigMap
metadata:
  name: busybox-cm
data:
  key1: value1
  key2: value2

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    name: busybox
spec:
  containers:
    - name: busybox
      image: "docker.io/library/busybox:latest"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      args:
        - sleep
        - "3600"
      volumeMounts:
        - name: test
          mountPath: /mnt/test
  volumes:
    - name: test
      configMap:
        name: busybox-cm
  restartPolicy: Never
