apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea_data
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: gitea
  labels:
    name: gitea
spec:
  containers:
    - name: gitea
      image: docker.io/bitnami/gitea:1
      resources:
        limits:
          memory: "2048Mi"
          cpu: "1000m"
      ports:
        - name: http
          containerPort: <Port>
