apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  # ref: https://github.com/jace-ys/vault-init/blob/309783a4ca0b88a691da7285200ec933b5738aea/docs/kubernetes/example.yaml
  config.hcl: |
    storage "raft" {
      path = "/vault/data"
      node_id = "vault"
    }

    # https://developer.hashicorp.com/vault/docs/configuration/ui#activating-the-vault-ui
    ui = true

    listener "tcp" {
      address = "0.0.0.0:8200"
      # https://developer.hashicorp.com/vault/docs/configuration/listener/tcp#tls_cert_file
      tls_cert_file = "/vault/data/sololab_vault.crt"
      tls_key_file = "/vault/data/sololab_vault.key"
    }

    api_addr = "http://127.0.0.1:8200"

    cluster_addr = "http://127.0.0.1:8201"