# Dynamic Configuration
http:
  routers:
    vault:
      rule: Host(`vault.infra.sololab`)
      entryPoints: 
        - websecure
      service: vault
      # https://doc.traefik.io/traefik/routing/routers/#tls
      # tls: true
  services:
    vault:
      loadBalancer:
        servers:
          - url: "http://vault:8200/"
