# code: language=ansible
---
- name: slurp yaml file
  ansible.builtin.slurp:
    src: "{{ podman_play.kube_file }}"
  register: kube_file_slurp
  delegate_to: localhost

- name: podman kube play
  when:
    - podman_play.state == "present"
  block:
    - name: Clean up the query params dict
      ansible.builtin.set_fact:
        podman_play_present_query_params: "{{ {item.key: item.value} }}"
      loop: "{{ podman_play.present.query_params | dict2items }}"
      when:
        - podman_play.present.query_params is defined
        - item.value is not none

    - name: Prepare query params for create
      ansible.builtin.set_fact:
        podman_play_present_query_params_string: "?{{ podman_play_present_query_params.keys() | 
                                                        ansible.builtin.zip(podman_play_present_query_params.values()) |
                                                        map('join', '=') |
                                                        join('&') }}"
      when: 
        - podman_play_present_query_params is defined

    - name: Run Podman kube play
      ansible.builtin.uri:
        url: "{{ podman_uri.host }}/{{ podman_uri.api_version }}/libpod/play/kube{{ podman_play_present_query_params_string | default('') }}"
        unix_socket: "{{ podman_unix_socket | default(omit) }}"
        method: POST
        status_code: 
          - 200
          - 500
        timeout: "{{ podman_play.timeout | default(300) }}"
        body_format: json
        body: "{{ kube_file_slurp.content | b64decode }}"
      register: podman_kube_play_respond
      changed_when: 
        - podman_kube_play_respond.status == 200
      
    - name: debug
      debug:
        msg: "{{ podman_kube_play_respond }}"

    - name: set pod id
      ansible.builtin.set_fact:
        pod_id: "{{ podman_kube_play_respond.json.Pods[0].ID }}"
      when:
        - podman_kube_play_respond.status == 200

    - name: debug
      debug:
        msg: "{{ pod_id }}"
      when:
        - podman_kube_play_respond.status == 200

- name: podman kube down
  when:
    - podman_play.state == "absent"
  block:
    - name: Clean up the query params dict
      ansible.builtin.set_fact:
        podman_play_absent_query_params: "{{ {item.key: item.value} }}"
      loop: "{{ podman_play.absent.query_params | dict2items }}"
      when:
        - podman_play.absent.query_params is defined
        - item.value is not none

    - name: Prepare query params for delete
      ansible.builtin.set_fact:
        podman_play_absent_query_params_string: "?{{ podman_play_absent_query_params.keys() | 
                                                        ansible.builtin.zip(podman_play_absent_query_params.values()) |
                                                        map('join', '=') |
                                                        join('&') }}"
      when:
        - podman_play_absent_query_params is defined

    - name: Run podman kube down
      ansible.builtin.uri:
        url: "{{ podman_uri.host }}/{{ podman_uri.api_version }}/libpod/play/kube{{ podman_play_absent_query_params_string | default('') }}"
        unix_socket: "{{ podman_unix_socket | default(omit) }}"
        method: DELETE
        status_code: 
          - 200
          - 500
        body_format: json
        body: "{{ kube_file_slurp.content | b64decode }}"
        return_content: true
      register: podman_kube_down_respond
      changed_when: 
        - podman_kube_down_respond.status == 200

    - name: debug
      debug:
        msg: "{{ podman_kube_down_respond }}"