# code: language=ansible
---
- name: create podman network {{ podman_network.request_body.name }}
  ansible.builtin.uri:
    url: http://d/{{ api_version }}/libpod/networks/create
    unix_socket: "{{ podman_unix_socket | default(omit) }}"
    method: POST
    status_code: 200
    body_format: json
    body: "{{ podman_network.request_body }}"
  when:
    - podman_network.state == "present"

- name: delete podman network {{ podman_network.request_body.name }}
  ansible.builtin.uri:
    url: http://d/{{ api_version }}/libpod/networks/{{ podman_network.request_body.name }}
    unix_socket: "{{ podman_unix_socket | default(omit) }}"
    method: DELETE
    status_code: 200