# code: language=ansible
---
- name: create podman network {{ podman_network.request_body.name }}
  ansible.builtin.uri:
    url: "{{ podman_uri.scheme_authority }}/{{ podman_uri.api_version }}/libpod/networks/create"
    unix_socket: "{{ podman_uri.unix_socket | default(omit) }}"
    method: POST
    body_format: json
    body: "{{ podman_network.present.request_body }}"
    status_code: 200
  when:
    - podman_network.state == "present"

- name: delete podman network {{ podman_network.request_body.name }}
  ansible.builtin.uri:
    url: "{{ podman_uri.scheme_authority }}/{{ podman_uri.api_version }}/libpod/networks/{{ podman_network.name }}"
    unix_socket: "{{ podman_uri.unix_socket | default(omit) }}"
    method: DELETE
    status_code: 200