# code: language=ansible
---
# tasks file for ansible-podman-rootless-play

# https://stackoverflow.com/questions/41725555/how-to-use-omit-with-ansible-and-avoid-any-errors
- name: Invoke podman network request
  ansible.builtin.include_tasks:
    file: Invoke-PodmanNetworkRequest.yml
  when:
    - (podman_network.state == "present") or (podman_network.state == "absent")
    - podman_network.name is not none

- name: Invoke podman play request
  ansible.builtin.include_tasks:
    file: Invoke-PodmanPlayRequest.yml
  when:
    - (podman_play.state == "present") or (podman_play.state == "absent")
    - podman_play.kube_file != none

- name: Detect pod info
  ansible.builtin.uri:
    url: "{{ podman_uri.scheme_authority }}/{{ podman_uri.api_version }}/libpod/pods/{{ pod_id | default(podman_generate_systemd.path_params.name) }}/json"
    unix_socket: "{{ podman_uri.unix_socket | default(omit) }}"
    method: GET
    status_code: 
      - 200
      - 404
    return_content: true
  register: pod_info

- name: debug
  debug:
    msg: "{{ pod_info }}"

- name: Invoke podman generate request
  ansible.builtin.include_tasks:
    file: Invoke-PodmanGenerateRequest.yml
  when:
    - pod_id | default(podman_generate_systemd.path_params.name)  is not none
