apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex.lab
  namespace: dex
spec:
  dnsNames:
    - dex.lab
  secretName: dex.lab
  issuerRef:
    name: issuer-selfsigned
    kind: ClusterIssuer