apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infra.sololab
  namespace: cert-manager
spec:
  dnsNames:
    - infra.sololab
  secretName: infra.sololab
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer