apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: solo.lab
  namespace: traefik
  # namespace: kube-system
spec:
  dnsNames:
    - solo.lab
  secretName: solo.lab
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer