apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: solo.lab
  namespace: kube-system
spec:
  dnsNames:
    - solo.lab
  secretName: solo.lab
  issuerRef:
    name: issuer-ca
    kind: ClusterIssuer