# code: language=ansible
---
- hosts: kube-1 # kube-2
  gather_facts: yes
  vars: 
    ipa:
      hostname: ipa.infra.sololab
    
    kube_file_template: /KubeWorkShop/Traefik/aio-traefik.yaml

    podman_rootless_play:
      vars_podman_host: kube-1
      vars_podman_uri:
        scheme_authority: http://d # http://d/ ← (default), https://docs.podman.io/en/latest/markdown/podman-system-service.1.html
        api_version: v4.4.1 # v4.0.0 ← (default)
        unix_socket: /run/user/1000/podman/podman.sock # socket file path for podman, e.g. /run/user/1000/podman/podman.sock
      vars_podman_play:
        state: present # absent / present
        timeout: 600
        kube_file: 
          host: localhost
          # path: /KubeWorkShop/Traefik/aio-traefik.yaml
          content: "{{ rendered }}"
        absent:
          query_params:
            force: true
      vars_podman_generate_systemd:
        generate:
          path_params: 
            name: traefik
          query_params:
            useName: true
      vars_service:
        podman_pod:
          user_scope:
            skipped: false
            enabled: true
            state: started

    dns:
      key_name: "keySololab"
      key_secret: "j/2DR2zkVAyDHL2XjE731sMt9s6cmRhXE6niScAgHA0="
      key_algorithm: "hmac-sha256"
      server: '192.168.255.31'
      zone: infra.sololab
      record: traefik
      value: '192.168.255.32'
      type: 'A'
      state: present

    ingress_file: /KubeWorkShop/Traefik/conf/dynamic/traefik-dashboard.yaml
  tasks:
    - name: Get root ca
      delegate_to: localhost
      block:
        - name: run openssl s_client -showcerts
          ansible.builtin.shell:
            # https://github.com/hashicorp/terraform-provider-aws/issues/10104#issuecomment-565547413
            cmd: >
              echo | 
              openssl s_client -showcerts -connect {{ ipa.hostname }}:443 2>&- | 
              tac | 
              sed -n '/-----END CERTIFICATE-----/,/-----BEGIN CERTIFICATE-----/p; /-----BEGIN CERTIFICATE-----/q' | 
              tac
          changed_when: false
          register: RootCACert

        - name: Set fact Root_CA_Cert
          ansible.builtin.set_fact:
            Root_CA_Cert: "{{ RootCACert.stdout }}"

    - name: Prepare kube_file content
      when:
        - Root_CA_Cert is defined
      block:
        - name: Render kube file content
          ansible.builtin.template:
            src: "{{ kube_file_template }}"
            dest: /dev/null
          check_mode: true
          diff: true
          no_log: false
          register: template

        - name: Set fact rendered
          ansible.builtin.set_fact:
            rendered: "{{ template.diff[0].after }}"

    - name: Invoke podman-rootless-play
      ansible.builtin.include_role:
        name: ansible-podman-rootless-play
      vars: 
        vars_podman_host: "{{ podman_rootless_play.vars_podman_host }}"
        vars_podman_uri: "{{ podman_rootless_play.vars_podman_uri }}"
        vars_podman_play: "{{ podman_rootless_play.vars_podman_play }}"
        vars_podman_generate_systemd: "{{ podman_rootless_play.vars_podman_generate_systemd }}"
        vars_service: "{{ podman_rootless_play.vars_service }}"

    - name: Config reverse proxy
      block:
        - name: Ensure dns record is present
          community.general.nsupdate: "{{ dns }}"
          delegate_to: localhost

        - name: present route config
          ansible.builtin.copy:
            src: "{{ ingress_file }}"
            dest: /home/{{ ansible_user }}/traefik/
          when: 
            - podman_rootless_play.vars_podman_play.state == 'present'

        - name: absent route config
          ansible.builtin.file:
            path: /home/{{ ansible_user }}/traefik/{{ ingress_file | basename }}
            state: absent
          when: 
            - podman_rootless_play.vars_podman_play.state == 'absent'