# code: language=ansible
---
- hosts: "{{ target_host }}" # kube-2
  gather_facts: yes
  vars:
    podman_rootless_play:
      vars_podman_host: "{{ target_host }}"
      vars_podman_uri:
        scheme_authority: http://d # http://d/ ← (default), https://docs.podman.io/en/latest/markdown/podman-system-service.1.html
        api_version: v4.4.1 # v4.0.0 ← (default)
        unix_socket: /run/user/{{ uid }}/podman/podman.sock # socket file path for podman, e.g. /run/user/1000/podman/podman.sock
      vars_podman_play:
        state: "{{ GitLab_pod_state }}" # absent / present
        timeout: 600
        kube_file:
          host: localhost
          content: "{{ lookup('ansible.builtin.template', GitLab_kube_file) }}"
        absent:
          query_params:
            force: true
      vars_podman_generate_systemd:
        generate:
          path_params:
            name: "{{ GitLab_systemd_service }}"
          query_params:
            useName: true
      vars_service:
        podman_pod:
          user_scope:
            skipped: false
            enabled: true
            state: started
  tasks:
    - name: Invoke podman-rootless-play
      ansible.builtin.include_role:
        name: ansible-podman-rootless-play
      vars: 
        vars_podman_host: "{{ podman_rootless_play.vars_podman_host }}"
        vars_podman_uri: "{{ podman_rootless_play.vars_podman_uri }}"
        vars_podman_play: "{{ podman_rootless_play.vars_podman_play }}"
        vars_podman_generate_systemd: "{{ podman_rootless_play.vars_podman_generate_systemd }}"
        vars_service: "{{ podman_rootless_play.vars_service }}"
