# code: language=ansible
---
- hosts: "{{ host_admin }}" # kube-2
  gather_facts: yes
  tasks:
    # https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#including-roles-dynamic-reuse
    - name: run role ansible-podman-rootless-provision
      ansible.builtin.include_role:
        name: ansible-podman-rootless-provision
      vars:
        target_user: "{{ podman.target_user }}"
        vars_package: "{{ podman.vars_package }}"
        vars_cgroups_delegation: "{{ podman.vars_cgroups_delegation }}"
        vars_pam_limits: "{{ podman.vars_pam_limits }}"
        vars_sub_ids: "{{ podman.vars_sub_ids }}"
        vars_kernel_modules: "{{ podman.vars_kernel_modules }}"
        vars_app_config: "{{ podman.vars_app_config }}"
        vars_service: "{{ podman.vars_service }}"
    # - name: whoami
    #   shell:
    #     cmd: id -u
    #   become_user: "{{ ansible_user }}"
    #   register: whoami
    # - name: debug
    #   debug:
    #     var: ansible_facts
