consul:
  ## hashicorp consul image
  ## ref: https://hub.docker.com/r/hashicorp/consul/tags/
  ## @param consul.image.registry consul image registry
  ## @param consul.image.repository consul image repository
  ## @param consul.image.tag consul image tag (immutable tags are recommended)
  ## @param consul.image.digest consul image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag image tag (immutable tags are recommended)
  ## @param consul.image.pullPolicy consul image pull policy
  ## @param consul.image.pullSecrets consul image pull secrets
  ##
  image:
    registry: zot.day0.sololab
    repository: hashicorp/consul
    tag: 1.18.2
  containerPorts:
    - name: server
      containerPort: 8300
      hostPort: 8300
      protocol: TCP
    - name: serf_lan-tcp
      containerPort: 8301
      hostPort: 8301
      protocol: TCP
    - name: serf_lan-udp
      containerPort: 8301
      hostPort: 8301
      protocol: UDP
    - name: http
      containerPort: 8500
      hostPort: 8500
      protocol: TCP
    - name: https
      containerPort: 8501
      hostPort: 8501
      protocol: TCP
    - name: grpc_tls
      containerPort: 8503
      hostPort: 8503
      protocol: TCP
    - name: dns-udp
      containerPort: 8600
      hostPort: 8600
      protocol: UDP
    - name: dns-tcp
      containerPort: 8600
      hostPort: 8600
      protocol: TCP
  ## @param consul.configFiles
  configFiles:
    general:
      ports:
        https: 8501
      # https://github.com/hashicorp/learn-consul-docker/blob/110bc9484b0dcd714e64604cd011a360d03b9bc6/datacenter-deploy-auto-config/vault/consul/server2.json#L33
      auto_config:
        authorization:
          enabled: true
          static:
            oidc_discovery_url: https://vault.day0.sololab:8200/v1/identity/oidc
            oidc_discovery_ca_cert: ## set via helm value
            bound_issuer: https://vault.day0.sololab:8200/v1/identity/oidc
            bound_audiences:
              - consul-cluster-dc1
            claim_mappings:
              /consul/hostname: node_name
            claim_assertions:
              - value.node_name == "${node}"
    acl:
      acl:
        enabled: true
        default_policy: deny
        enable_token_persistence: true
        tokens:
          initial_management: e95b599e-166e-7d80-08ad-aee76e7ddf19
          agent: e95b599e-166e-7d80-08ad-aee76e7ddf19
          config_file_service_registration: e95b599e-166e-7d80-08ad-aee76e7ddf19
    encryption:
      encrypt: aPuGh+5UDskRAbkLaXRzFoSOcSM+5vAK+NEYOWHJH7w=
    tls:
      tls:
        defaults:
          ca_file: /consul/config/certs/ca.crt
          cert_file: /consul/config/certs/server.crt
          key_file: /consul/config/certs/server.key
          verify_incoming: false
          verify_outgoing: true
        internal_rpc:
          verify_server_hostname: true
  ## @param consul.command Override default container command (useful when using custom images)
  ## ref: https://github.com/hashicorp/consul/blob/main/.release/docker/docker-entrypoint.sh#L75
  ## this command is used to set the advertise ip to host ip when consul start
  ## in detail, this script insert "-advertise=<host ip>" in the next line of string "$CONSUL_BIND \"
  ## before:
  ## set -- consul agent \
  ##   -data-dir="$CONSUL_DATA_DIR" \
  ##   -config-dir="$CONSUL_CONFIG_DIR" \
  ##   $CONSUL_BIND \
  ##   $CONSUL_CLIENT \
  ##   "$@"
  ##
  ## after:
  ## set -- consul agent \
  ##   -data-dir="$CONSUL_DATA_DIR" \
  ##   -config-dir="$CONSUL_CONFIG_DIR" \
  ##   $CONSUL_BIND \
  ##   -advertise=<host ip> \
  ##   $CONSUL_CLIENT \
  ##   "$@"
  command:
    - "/bin/sh"
    - "-c"
    - |
      sed -e '/$CONSUL_BIND \\/i\' -e '    -advertise=$(getent hosts host.containers.internal | awk '\''{print $1}'\'') \\' /usr/local/bin/docker-entrypoint.sh > /tmp/docker-entrypoint.sh
      chmod +x /tmp/docker-entrypoint.sh
      exec /tmp/docker-entrypoint.sh "$0" "$@"
