apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns.fullname" . }}
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_PASS: {{ required "Missing variable: mariadb.auth.password" .Values.mariadb.auth.password | b64enc}}
  MYSQL_ROOT_PASS: {{ required "Missing variable: mariadb.auth.rootPassword" .Values.mariadb.auth.rootPassword | b64enc}}