apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-smb-samba
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-samba
  storageClassName: ""