global:
  imageRegistry: zot.day0.sololab
nomad:
  image:
    repository: multani/nomad
    tag: "1.9.5"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 300
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - nomad
        - server
        - members
        - -tls-skip-verify
        - -address
        - https://localhost:4646
  configFiles:
    main:
      acl:
        enabled: true
      tls:
        http: true
        rpc: true
        ca_file: "/nomad/config/certs/ca.crt"
        cert_file: "/nomad/config/certs/server.crt"
        key_file: "/nomad/config/certs/server.key"

  args:
    - agent
  extraEnvVars:
    - name: NOMAD_DISABLE_PERM_MGMT
      value: "ture"
    # env var for image multani/nomad
    # https://github.com/multani/docker-nomad/blob/9f5cc384481214f0232b38262b0512c2d22a0887/v1.9.x/start.sh#L15
    - name: NOMAD_CONFIG_DIR
      value: /nomad/config
    - name: TZ
      value: Asia/Shanghai
