global:
  imageRegistry: zot.day0.sololab
kea:
  containers:
    dhcp4:
      containerPorts: []
      extraEnvVars:
        - name: TZ
          value: Asia/Shanghai
      config:
        Dhcp4:
          subnet4:
            - subnet: 192.168.255.0/24
              pools:
                - pool: 192.168.255.100-192.168.255.200
              id: 1
              interface: eth0
              option-data:
                - name: domain-name-servers
                  data: 192.168.255.1,192.168.255.10
