# code: language=ansible
---
- hosts: kube-1 # kube-2
  gather_facts: no
  vars:
    api_version: v4.0.0
    unix_socket: /run/user/1000/podman/podman.sock
    podman_network:
      state: absent
      request_body:
        created: # string <date-time>, Created contains the timestamp when this network was created.
        dns_enabled: # boolean, true / false
        driver: # Driver for this Network, e.g. bridge, macvlan
        id: # ID of the Network.
        internal: # boolean, Internal is whether the Network should not have external routes to public or other Networks
        ipam_options: # object, IPAMOptions contains options used for the ip assignment.
        ipv6_enabled: # boolean, IPv6Enabled if set to true an ipv6 subnet should be created for this net.
        labels: # object(dict), Labels is a set of key-value labels that have been applied to the Network.
        name: # string, Name of the Network.
        network_dns_servers: # Array of strings, List of custom DNS server for podman's DNS resolver at network level, all the containers attached to this network will consider resolvers configured at network level.
        network_interface: # string, NetworkInterface is the network interface name on the host.
        options: # object, Options is a set of key-value options that have been applied to the Network.
        subnets: # Array of objects (Subnet), Subnets to use for this network.
  tasks:
    - name: debug
      debug:
        msg: "{{ podman_network.request_body }}"

    - name: new podman network
      ansible.builtin.uri:
        url: http://d/{{ api_version }}/libpod/networks/create
        unix_socket: "{{ unix_socket }}"
        method: POST
        status_code: 200
        body_format: json
        body: "{{ podman_network.request_body }}"
      when:
        - podman_network.state == "present"
        - podman_network.request_body.name is defined
        - podman_network.request_body.name is not none

    - name: Delete podman network
      ansible.builtin.uri:
        url: http://d/{{ api_version }}/libpod/networks/{{ podman_network.request_body.name }}
        unix_socket: "{{ unix_socket }}"
        method: DELETE
        status_code: 200
      when:
        - podman_network.state == "absent"
        # https://blog.csdn.net/weixin_43384009/article/details/105212822
        - podman_network.request_body.name is defined
        - podman_network.request_body.name is not none