apiVersion: v1
kind: ConfigMap
metadata:
  name: samba
data:
  config.json: |
    {
      "_NOTE1": "https://github.com/samba-in-kubernetes/samba-container/blob/e42bb52a8a624e37547ec39ce5f1f38c636d9f96/examples/podman/config.json",
      "_NOTE2": "https://github.com/samba-in-kubernetes/sambacc/blob/ae4bf96cba0cd9dab9e95c03482f66833d5ce7c5/examples/minimal.json",
      "samba-container-config": "v0",
      "configs": {
        "demo": {
          "shares": [
            "share"
          ],
          "globals": [
            "default"
          ],
          "instance_name": "SAMBA"
        }
      },
      "shares": {
        "_NOTE3": "https://github.com/samba-in-kubernetes/sambacc/blob/a24d4dea719b201075af36fa3d31d87ab1ca4f15/tests/test_config.py#L79",
        "_NOTE4": "https://www.samba.org/samba/docs/using_samba/ch09.html",
        "share": {
          "options": {
            "path": "/share",
            "valid users": "sambauser",
            "writable": "yes"
          }
        }
      },
      "globals": {
        "default": {
          "options": {
            "security": "user",
            "server min protocol": "SMB2",
            "load printers": "no",
            "printing": "bsd",
            "printcap name": "/dev/null",
            "disable spoolss": "yes",
            "guest ok": "no"
          }
        }
      },
      "users": {
        "_NOTE": "https://github.com/samba-in-kubernetes/sambacc/blob/a24d4dea719b201075af36fa3d31d87ab1ca4f15/tests/test_config.py#L150",
        "all_entries": [
          {
            "name": "sambauser",
            "uid": 0,
            "gid": 0,
            "password": "samba"
          }
        ]
      },
      "_footer": 1
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: samba
  labels:
    name: samba
spec:
  # https://github.com/samba-in-kubernetes/samba-container/tree/master
  # https://github.com/samba-in-kubernetes/samba-container/blob/master/examples/kubernetes/sambapod.yml
  containers:
    - name: samba
      image: quay.io/samba.org/samba-server:v0.2
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: smb
          containerPort: 445
      env:
        - name: SAMBACC_CONFIG
          value: /etc/samba-container/config.json
      volumeMounts:
        # https://www.cnblogs.com/liugp/p/16651760.html
        # https://dev.to/joshduffney/kubernetes-using-configmap-subpaths-to-mount-files-3a1i
        # SubPaths are not automatically updated when a ConfigMap is modified.
        # but subpath have not support from podman
        # https://github.com/containers/podman/issues/12929
        # update: subpath was supported in podman v4.4+
        - name: samba_config
          mountPath: /etc/samba-container/config.json
          subPath: config.json
        - name: samba_share
          mountPath: /share
  volumes:
    - name: samba_config
      # https://kubernetes.io/docs/concepts/storage/volumes/#configmap
      configMap:
        name: samba
        items:
          - key: config.json
            path: config.json
    - name: samba_share
      hostPath:
        # path: /home/vagrant/infra/
        path: /home/vagrant/.local/share/containers/storage/volumes/
        type: Directory
  restartPolicy: Never
