# k3s use kube-router as default netowork policy controller
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web-deny-all
  namespace: kube-dashboard
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: k8s-dashboard
  ingress: []