# https://ansible-builder.readthedocs.io/en/latest/definition/
# https://ansible.readthedocs.io/projects/builder/en/stable/definition/#version-3-format
---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: |
    collections:
      - ansible.utils
      - ansible.posix
      - community.crypto
      - community.general
      - community.hashi_vault
      - kubernetes.core
      - vyos.vyos
  python:
    - netaddr
    - pyyaml # required by kubernetes.core.k8s module
    - kubernetes # required by kubernetes.core.k8s module
    - jsonpatch # required by kubernetes.core.k8s module
    - jmespath # required by community.general.json_query module
    - dnspython # required by community.general.nsupdate module
    - cryptography # required by community.crypto.get_certificate module
    - hvac # required by community.hashi_vault module
  system:
    - git
    - unzip
    - python3-ldap
    - sshpass

images:
  base_image:
    name: quay.io/centos/centos:stream9

additional_build_steps:
  # prepend_galaxy: |
  #   RUN find /output/scripts/ -type f -exec chmod +x {} \;
  # prepend_builder: |
  #   RUN find /output/scripts/ -type f -exec chmod +x {} \;
  prepend_final:
    # - RUN find /output/scripts/ -type f -exec chmod +x {} \;
    - RUN dnf install 'dnf-command(config-manager)' -y && dnf config-manager --set-enabled crb && dnf install epel-release epel-next-release -y
  append_final:
    - ARG PROXY
    - ARG TERRAFORM_VERSION=1.4.6

    - RUN cd /tmp &&
      curl -LO https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_amd64.zip &&
      unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip &&
      install -o root -g root -m 0755 terraform /usr/local/bin/terraform

    - RUN curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl &&
      ls -al /usr/local/bin/kubectl &&
      chmod 0755 /usr/local/bin/kubectl

    - RUN curl -L https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-linux-amd64 -o /usr/local/bin/helm &&
      chmod +x /usr/local/bin/helm

    - RUN export HTTPS_PROXY=${PROXY} &&
      export HTTP_PROXY=${PROXY} &&
      export https_proxy=${PROXY} &&
      export http_proxy=${PROXY} &&
      /usr/local/bin/helm plugin install https://github.com/databus23/helm-diff &&
      unset HTTPS_PROXY &&
      unset HTTP_PROXY &&
      unset https_proxy &&
      unset http_proxy
