---
sololab:
  vars:
    # https://9to5answer.com/can-i-bypass-host-key-checking-in-ansible
    # https://github.com/ansible/ansible/issues/49254
    ansible_host_key_checking: False
    ansible_ssh_host_key_checking: False
  hosts:
    vyos:
      ansible_host: 192.168.255.1
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: vyos.vyos.vyos
      ansible_user: vagrant
      ansible_password: vagrant
    kube-0:
      ansible_user: vagrant
      ansible_host: localhost
      ansible_python_interpreter: /usr/bin/python3
      # ansible_ssh_private_key_file: ~/.ssh/vagrant
    kube-1:
      ansible_user: vagrant
      # https://riptutorial.com/ansible/example/5733/inventory-with-username-and-password
      # ansible_ssh_pass: vagrant
      ansible_host: 192.168.255.31
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: /tmp/ssh.key
    kube-2:
      ansible_user: vagrant
      # https://riptutorial.com/ansible/example/5733/inventory-with-username-and-password
      # ansible_ssh_pass: vagrant
      ansible_host: 192.168.255.11
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: /tmp/ssh.key
    kube-3:
      ansible_user: vagrant
      # https://riptutorial.com/ansible/example/5733/inventory-with-username-and-password
      ansible_ssh_pass: vagrant
      ansible_host: 192.168.255.12
      # ansible_python_interpreter: /usr/bin/python3
      # ansible_ssh_private_key_file:  ~/.ssh/vagrant
