---
Cloud:
  vars:
    # https://9to5answer.com/can-i-bypass-host-key-checking-in-ansible
    # https://github.com/ansible/ansible/issues/49254
    ansible_host_key_checking: False
    ansible_ssh_host_key_checking: False
  hosts:
    gitlab:
      ansible_user: podmgr
      # https://riptutorial.com/ansible/example/5733/inventory-with-username-and-password
      # ansible_ssh_pass: vagrant
      ansible_host: gitlab.devops.p2w3
      ansible_python_interpreter: /usr/bin/python3
      ansible_ssh_private_key_file: ~/.ssh/ssh.key
