apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  labels:
    name: keycloak
spec:
  containers:
    - name: postgresql
      image: docker.io/bitnami/postgresql:15.1.0
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: postgresql
          containerPort: 5432
      env:
        - name: POSTGRESQL_USERNAME
          value: bn_keycloak
        - name: POSTGRESQL_PASSWORD
          value: password
        - name: POSTGRESQL_DATABASE
          value: bitnami_keycloak
      volumeMounts:
        - name: postgresql_data
          mountPath: /bitnami/postgresql

    - name: keycloak
      image: quay.io/keycloak/keycloak:20.0
      resources:
        limits:
          memory: "512Mi"
          cpu: "1000m"
      ports:
        - name: http
          containerPort: 8080
        # - name: https
        #   containerPort: 8443
      # https://www.keycloak.org/server/all-config
      # https://github.com/zak905/extending-keycloak-udemy-course/blob/fb271e99b7091ab39fcca76ef21387bdbb1407ce/docker-compose.yaml
      env:
        # https://www.keycloak.org/server/configuration
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: password

        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: keycloak
        - name: KC_DB_URL_DATABASE
          value: bitnami_keycloak
        - name: KC_DB_USERNAME
          value: bn_keycloak
        - name: KC_DB_PASSWORD
          value: password

        # production mode need hostname and tls cert
        # hostname will force redirect url to the fqdn of
        # hostname value in browser
        # - name: KC_HOSTNAME
        #   value: keycloak

        # the way to import realm
        # 1. use JAVA_OPTS_APPEND
        # 2. use --import-realm + data in /opt/keycloak/data/import/
        # - name: JAVA_OPTS_APPEND
        #   value: -Dkeycloak.import=/opt/keycloak/data/import/freeipa-realm.json
      args:
        - 'start-dev'
        # https://www.keycloak.org/server/importExport#_importing_a_realm_during_startup
        - '--import-realm'
      volumeMounts:
        - name: keycloak_config
          mountPath: /opt/keycloak/data/import/
  volumes:
    - name: postgresql_data
      hostPath:
        path: /home/vagrant/infra/keycloak/postgresql/
        type: Directory
    - name: keycloak_config
      configMap:
        name: keycloak
        items:
          - key: freeipa-realm.json
            path: freeipa-realm.json
  restartPolicy: Never