# code: language=ansible
---
- hosts: kube-1 # kube-2
  gather_facts: yes
  tasks:
     # https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#including-roles-dynamic-reuse
    - name: run role ansible-podman-rootless-provision
      ansible.builtin.include_role:
        name: ansible-podman-rootless-provision
      vars:
        vars_podman_volume:
          name:  samba
          state: present
        vars_podman_play:
          kube_file: /KubeWorkShop/Samba/aio-consul.yaml
        vars_podman_generate_systemd:
          state: present
          dest: ~/.config/systemd/user/