# code: language=ansible
---
- hosts: kube-2 # kube-2
  gather_facts: yes
  tasks:
     # https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#including-roles-dynamic-reuse
    - name: run role ansible-podman-rootless-provision
      ansible.builtin.include_role:
        name: ansible-podman-rootless-provision
      vars:
        vars_package:
          podman:
            state: present
        vars_cgroups_delegation:
          all_users:
            state: present
            present_override: false
            resources: cpu
          per_user:
            state: skipped
            resources: io
        vars_sub_ids:
          state: present
          present_override: false
        # vars_kernel_modules:
        #   state: skipped
        # vars_pam_limits:
        #   state: present
    # - name: whoami
    #   shell:
    #     cmd: id -u
    #   become_user: "{{ ansible_user }}"
    #   register: whoami
    # - name: debug
    #   debug:
    #     var: ansible_facts