opendj:
  image:
    registry: zot.day0.sololab
    repository: openidentityplatform/opendj
    tag: 4.8.2
  extraEnvVars:
    - name: TZ
      value: Asia/Shanghai
  # %%OTHER_PARAMETERS_RELATED_TO_THIS_CONTAINER/POD%%
  ## @param opendj.setupProperties properties config when opendj setup
  ## aka environment variable for the opendj image
  ## ref: https://github.com/OpenIdentityPlatform/OpenDJ/blob/master/opendj-packages/opendj-docker/README.md
  ##
  setupProperties:
    ## @param opendj.setupProperties.BASE_DN OpenDJ Base DN
    ##
    BASE_DN: dc=root,dc=sololab
    ## @param opendj.setupProperties.ROOT_PASSWORD Initial root user password
    ##
    ROOT_PASSWORD: P@ssw0rd
    ## @param opendj.setupProperties.OPENDJ_SSL_OPTIONS you can replace ssl options at here,
    ## like : "--usePkcs12keyStore /opt/domain.pfx --keyStorePassword domain"
    ##
    OPENDJ_SSL_OPTIONS: "--usePkcs12keyStore /opt/opendj/certs/keystore.pfx --keyStorePassword changeit"
