# https://github.com/puckpuck/helm-charts/blob/main/charts/powerdns/values.yaml

service:
  type: LoadBalancer

mariadb:
  rootUser:
    password: password
  master:
    persistence:
      enabled: true