expose:
  ingress:
    hosts:
      core: core.harbor.lab
      notary: notary.harbor.lab
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
externalURL: https://core.harbor.lab
harborAdminPassword: "Harbor12345"