# code: language=ansible
---
- hosts: kube-1 # kube-2
  gather_facts: yes
  vars: 
    ipa_hostname: ipa.infra.sololab
  tasks:
    - name: Get root ca
      delegate_to: localhost
      block:
        - name: Get cookie for service ipa
          ansible.builtin.uri:
            url: "https://{{ ipa_hostname }}/ipa/session/login_password"
            validate_certs: false
            method: POST
            headers:
              Referer: https://{{ ipa_hostname }}/ipa
              Accept: text/plain
              Content-Type: "application/x-www-form-urlencoded"
            body_format: form-urlencoded
            body:
              user: "admin"
              password: "P@ssw0rd"
            status_code: 200
          register: ipa_session

        - name: Get CA root cert
          ansible.builtin.uri:
            url: "https://{{ ipa_hostname }}/ipa/session/json"
            validate_certs: false
            method: POST
            headers:
              Referer: https://{{ ipa_hostname }}/ipa
              Accept: application/json
              Cookie: "{{ ipa_session.set_cookie }}"
            body_format: json
            body:
              id: 0
              method: cert_show/1
              params:
                # serial_number
                - - 1
                # Include certificate chain in output
                - chain: true
                  raw: true
            status_code: 200
            return_content: true
          register: Root_CA_Cert
          when:
            - ipa_session is defined

        - name: Render minio kube_file
          ansible.builtin.template:
            src: /KubeWorkShop/MinIO/aio-minio.yaml
            dest: /KubeWorkShop/MinIO/aio-minio-rendered.yaml

    - name: incloude vars
      ansible.builtin.include_vars:
        file: vars/podman_play-minio.yml

     # https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#including-roles-dynamic-reuse
    - name: run role ansible-podman-rootless-provision
      ansible.builtin.include_role:
        name: ansible-podman-rootless-play

    - name: Ensure dns record is present
      community.general.ipa_dnsrecord:
        ipa_host: ipa.infra.sololab
        ipa_pass: P@ssw0rd
        validate_certs: false
        zone_name: infra.sololab
        record_name: minio
        record_type: 'A'
        record_value: '192.168.255.32'
        state: present

    - name: present minio traefik config
      ansible.builtin.copy:
        src: /KubeWorkShop/MinIO/traefik-minio.yaml
        dest: /home/{{ ansible_user }}/traefik/