# code: language=ansible
---
- hosts: kube-1 # kube-2
  gather_facts: yes
  tasks:
     # https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#including-roles-dynamic-reuse
    - name: run role ansible-podman-rootless-provision
      ansible.builtin.include_role:
        name: ansible-podman-rootless-provision
      vars:
        vars_package:
          podman:
            state: absent
            dnf:
              enablerepo: updates-testing
              update_cache: true
        vars_cgroups_delegation:
          all_users:
            state: present
            present_override: false
            resources: cpu cpuset io memory pids
          per_user:
            state: skipped
            resources: io
        vars_pam_limits:
          state: present
        vars_sub_ids:
          state: present
          present_override: false
        vars_app_config:
          podman:
            containers_conf:
              state: present
              content: |
                [containers]
                # log_driver="k8s-file"
                # log_size_max="10m"
                shm_size="128m"
                tz = "Asia/Shanghai"
    # - name: whoami
    #   shell:
    #     cmd: id -u
    #   become_user: "{{ ansible_user }}"
    #   register: whoami
    # - name: debug
    #   debug:
    #     var: ansible_facts