# code: language=ansible
---
- hosts: localhost # kube-2
  gather_facts: yes
  vars: 
    ipa_hostname: ipa.infra.sololab
  tasks:
    - name: Get root ca
      block:
        - name: Get cookie for service ipa
          ansible.builtin.uri:
            url: "https://{{ ipa_hostname }}/ipa/session/login_password"
            validate_certs: false
            method: POST
            headers:
              Referer: https://{{ ipa_hostname }}/ipa
              Accept: text/plain
              Content-Type: "application/x-www-form-urlencoded"
            body_format: form-urlencoded
            body:
              user: "admin"
              password: "P@ssw0rd"
            status_code: 200
          register: ipa_session

        - name: Get CA root cert
          ansible.builtin.uri:
            url: "https://{{ ipa_hostname }}/ipa/session/json"
            validate_certs: false
            method: POST
            headers:
              Referer: https://{{ ipa_hostname }}/ipa
              Accept: application/json
              Cookie: "{{ ipa_session.set_cookie }}"
            body_format: json
            body:
              id: 0
              method: cert_show/1
              params:
                # serial_number
                - - 1
                # Include certificate chain in output
                - chain: true
                  raw: true
            status_code: 200
            return_content: true
          register: CA_Cert
          when:
            - ipa_session is defined

    - name: Render traefik kube_file
      ansible.builtin.template:
        src: /KubeWorkShop/Traefik/aio-traefik.yaml.j2
        dest: /KubeWorkShop/Traefik/aio-traefik-rendered.yaml

    - name: cat
      shell:
        cmd: cat /KubeWorkShop/Traefik/aio-traefik-rendered.yaml
      register: cat
    - name: debug
      debug:
        msg: "{{ cat }}"
    # - name: incloude vars
    #   ansible.builtin.include_vars:
    #     file: "{{ podman_play_var_file }}"

    #  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#including-roles-dynamic-reuse
    # - name: run role ansible-podman-rootless-provision
    #   ansible.builtin.include_role:
    #     name: ansible-podman-rootless-play
