# code: language=ansible
---
- hosts: localhost
  gather_facts: false
  vars:
    # https://serverfault.com/questions/907164/ansible-conditionally-define-variables-in-vars-file-if-a-certain-condition-is-m
    case_service_podman_user_socket_present:
      socket_openrc_directory: directory
      socket_state: started
      socket_enabled: true

    case_service_podman_user_socket_absent:
      socket_openrc_directory: absent
      socket_state: stopped
      socket_enabled: false

    case_service_podman_system_socket_present:
      socket_state: started
      socket_enabled: true
      
    case_service_podman_system_socket_absent:
      socket_state: stopped
      socket_enabled: false

    package_podman_state: absent
    service_podman_user_socket: present
    service_podman_system_socket: absent

    service_podman_user_socket_final: "{% if package_podman_state == 'absent' %}absent{% else %}{{ service_podman_user_socket }}{% endif %}"
    service_podman_system_socket_final: "{% if package_podman_state == 'absent' %}absent{% else %}{{ service_podman_system_socket }}{% endif %}"

    service_podman_user: "{{ lookup('vars','case_service_podman_user_socket_' + service_podman_user_socket_final) }}"
    service_podman_system: "{{ lookup('vars','case_service_podman_system_socket_' + service_podman_system_socket_final) }}"
  tasks:
    - name: test
      ansible.builtin.debug:
        msg: 
          - service_podman_user
          - "{{ service_podman_user }}"
          - "{{ service_podman_user.socket_openrc_directory }}"
          - service_podman_system
          - "{{ service_podman_system }}"
          - "{{ service_podman_system.socket_enabled }}"