# code: language=ansible
---
- hosts: localhost
  gather_facts: false
  vars:
    # var_terraform_folder: "{{ playbook_dir }}/terraform/"
    var_terraform_folder: "/TerraformWorkShop/Local/Certs"
  tasks:
    - name: Create selfsign CA
      block:
      - name: include_vars
        community.general.terraform:
          project_path: "{{ var_terraform_folder }}"
          force_init: true
          overwrite_init: false
          state: present
      