---
- hosts: localhost
  gather_facts: true
  vars: 
    kube_node: "kube-1"  
  tasks:
    - name: debug
      ansible.builtin.debug:
        msg: "{{ lookup('ansible.builtin.file', '/etc/rancher/k3s/config.yaml') }}"
      delegate_to: "{{ kube_node }}"