# Static Configuration

## Configuration Discovery
# https://doc.traefik.io/traefik/providers/overview/
providers:
# https://doc.traefik.io/traefik/providers/file/#directory
  file:
    directory: /etc/traefik/dynamic
    watch: true

# ref: https://www.vtulluru.com/how-to-install-traefik-as-a-container-using-docker-or-podman/
# https://doc.traefik.io/traefik/reference/static-configuration/file/
global:
  checkNewVersion: false
  sendAnonymousUsage: false


## Routing & Load Balancing
# https://doc.traefik.io/traefik/routing/overview/
entryPoints:
  # https://doc.traefik.io/traefik/routing/entrypoints/#entrypoints
  # https://doc.traefik.io/traefik/routing/routers/#configuration-example
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: ":443"

# https://doc.traefik.io/traefik/routing/overview/#transport-configuration
# serversTransport:
#   # https://doc.traefik.io/traefik/routing/overview/#rootcas
#   rootCAs:
#     - /etc/traefik/root_ca.crt


## Operations
# https://doc.traefik.io/traefik/operations/api/
api:
  dashboard: true

# https://smallstep.com/docs/tutorials/acme-protocol-acme-clients#traefik
# https://doc.traefik.io/traefik/https/acme/#certificate-resolvers
certificatesResolvers:
  freeipa:
    acme:
      caServer: https://ipa-ca.infra.sololab/acme/directory
      email: admin@INFRA.SOLOLAB
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

## Observability
log:
  level: DEBUG

accessLog: {}
  