# https://rancher.com/docs/k3s/latest/en/helm/#customizing-packaged-components-with-helmchartconfig
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesIngress:
        ingressClass: "traefik"
    # Enable HTTPS redirection on web entrypoint
    additionalArguments:
      - --entryPoints.web.http.redirections.entryPoint.to: websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme: https
    securityContext:
      capabilities:
        drop: [ALL]
        add: [NET_BIND_SERVICE]
      readOnlyRootFilesystem: true
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0