---
# defaults file for infra
certman_resources_dir: "{{ role_path }}/templates/CertMan"

traefik_helm_values_path: "{{ role_path }}/templates/Traefik/values.yaml"
traefik_resources_dir: "{{ role_path }}/templates/Traefik"

dex_helm_values_path: "{{ role_path }}/templates/Dex/values.yaml"
dex_resources_dir: "{{ role_path }}/templates/Dex"

coreDNS_resources_dir: "{{ role_path }}/templates/CoreDNS"

loginapp_helm_values_path: "{{ role_path }}/templates/Loginapp/values.yaml"