# code: language=ansible
# cd "$(git rev-parse --show-toplevel)\AnsibleWorkShop\runner"
# $private_data_dir = "/tmp/private"
# podman run --rm --userns=keep-id `
#   --dns 192.168.255.10 `
#   -v ./:$private_data_dir `
#   -e RUNNER_PLAYBOOK=./debug/Invoke-ConsulRequest.yml `
#   -e ANSIBLE_DISPLAY_SKIPPED_HOSTS=False `
#   localhost/ansible-ee-aio-new `
#   bash -c "ansible-runner run $private_data_dir -vv"
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: test
      community.general.consul:
        host: consul.infra.sololab
        port: 443
        scheme: https
        validate_certs: false
        token: e95b599e-166e-7d80-08ad-aee76e7ddf19
        service_name: ipa
        service_address: 192.168.255.10
        service_port: 443
        tcp: ipa.infra.sololab:443
        interval: 2m
        state: present
        tags:
          - traefik.enable=true
    # - name: catalog - register
    #   ansible.builtin.uri:
    #     # url: "https://consul.infra.sololab/v1/agent/service/register"
    #     url: "https://consul.infra.sololab/v1/agent/service/deregister/ipa.infra.sololab"
    #     validate_certs: false
    #     method: PUT
    #     headers:
    #       X-Consul-Token: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
        # body_format: json
        # # https://github.com/eclipse-slm/slm-ansible-role-consul/blob/e166a70be3dd7706635a3f87e46057a283f75929/consul/tasks/helper/restore_node_and_services.yml#L13
        # body: 
        #   Name: ipa.infra.sololab
        #   Address: ipa.infra.sololab
        #   Port: 443
          # Service:
          #   Service: "ipa.infra.sololab"
          #   Address: "ipa.infra.sololab"
          #   Port: 443
          #   Tags:
          #     - traefik.enable=true
          # Check:
          #   Node: "{{ consul_node_name }}"
          #   Name: http-check
          #   status: passing
          #   Definition:
          #     http: "{{ consul_service_metrics_scheme }}://{{ consul_node_address }}"
          #     interval: 30s
  
