# code: language=ansible
# cd "$(git rev-parse --show-toplevel)\AnsibleWorkShop\runner"
# $private_data_dir = "/tmp/private"
# podman run --rm --userns=keep-id `
#   --dns 192.168.255.10 `
#   -v ./:$private_data_dir `
#   -e RUNNER_PLAYBOOK=./debug/Invoke-ConsulRequest.yml `
#   -e ANSIBLE_DISPLAY_SKIPPED_HOSTS=False `
#   localhost/ansible-ee-aio-new `
#   bash -c "ansible-runner run $private_data_dir -vv"
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: consul service
      community.general.consul:
        host: consul.infra.sololab
        port: 443
        scheme: https
        validate_certs: false
        token: e95b599e-166e-7d80-08ad-aee76e7ddf19
        service_name: ipa
        service_address: 192.168.255.10
        service_port: 443
        tcp: ipa.infra.sololab:443
        interval: 2m
        state: present
        tags:
          - traefik.enable=true
      when: false
    
    - name: consul kv
      community.general.consul_kv:
        host: consul.infra.sololab
        port: 443
        scheme: https
        validate_certs: false
        token: e95b599e-166e-7d80-08ad-aee76e7ddf19

        key: config/service_unit
        value: |
          [Unit]
          Description="HashiCorp Consul - A service mesh solution"
          Documentation=https://www.consul.io/
          Requires=network-online.target
          After=network-online.target
          ConditionFileNotEmpty=/etc/consul.d/consul.hcl

          [Service]
          EnvironmentFile=-/etc/consul.d/consul.env
          ExecStart=/usr/bin/consul agent -config-dir=/etc/consul.d/
          ExecReload=/bin/kill --signal HUP $MAINPID
          KillMode=process
          KillSignal=SIGTERM
          Restart=on-failure
          LimitNOFILE=65536

          [Install]
          WantedBy=multi-user.target
        state: present
    