# code: language=ansible
# cd "$(git rev-parse --show-toplevel)\AnsibleWorkShop\runner"
# $private_data_dir = "/tmp/private"
# podman run --rm --userns=keep-id `
#   --dns 192.168.255.10 `
#   -v ./:$private_data_dir `
#   -e RUNNER_PLAYBOOK=./debug/Invoke-ConsulRequest.yml `
#   -e ANSIBLE_DISPLAY_SKIPPED_HOSTS=False `
#   localhost/ansible-ee-aio-new `
#   bash -c "ansible-runner run $private_data_dir -vv"
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: consul service
      community.general.consul:
        host: consul.infra.sololab
        port: 443
        scheme: https
        validate_certs: false
        token: e95b599e-166e-7d80-08ad-aee76e7ddf19
        service_name: ipa
        service_address: 192.168.255.10
        service_port: 443
        tcp: ipa.infra.sololab:443
        interval: 2m
        state: present
        tags:
          - traefik.enable=true
      when: false
    
    - name: consul service
      uri:
        url: "https://consul.infra.sololab/v1/agent/service/register"
        validate_certs: false
        method: PUT # DELETE
        headers:
          X-Consul-Token: e95b599e-166e-7d80-08ad-aee76e7ddf19
        body_format: json
        body: 
          ID:
          Name:
          Address:
          Port:
          Tags:
      when: false

    - name: consul kv
      uri:
        url: "https://consul.infra.sololab/v1/kv/{{ item.key }}"
        validate_certs: false
        method: PUT # DELETE
        headers:
          X-Consul-Token: e95b599e-166e-7d80-08ad-aee76e7ddf19
        body: "{{ item.value }}"
      loop:
        - key: config/client
          # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_advanced_syntax.html#advanced-playbook-syntax
          value: !unsafe |
            acl {
              tokens {
                agent = "e95b599e-166e-7d80-08ad-aee76e7ddf19"
              }
            }
            bind_addr = "{{ GetInterfaceIP `eth0` }}"
            datacenter = "dc1"
            data_dir = "/home/podmgr/consul/data"
            encrypt = "qDOPBEr+/oUVeOFQOnVypxwDaHzLrD+lvjo5vCEBbZ0="
            retry_join = [
              "consul.infra.sololab"
            ]

        - key: config/systemd
          value: |
            [Unit]
            Description="HashiCorp Consul - A service mesh solution - 123"
            Documentation=https://www.consul.io/
            Wants=network-online.target
            After=network-online.target
            ConditionFileNotEmpty=/home/podmgr/consul/config/consul.hcl

            [Service]
            EnvironmentFile=-/home/podmgr/consul/config/consul.env
            ExecStart=/usr/bin/consul agent -config-dir=/home/podmgr/consul/config/
            ExecReload=/bin/kill --signal HUP $MAINPID
            KillMode=process
            KillSignal=SIGTERM
            Restart=on-failure
            LimitNOFILE=65536

            [Install]
            WantedBy=default.target

        - key: config/script
          value: !unsafe |
            #! /bin/bash
            mkdir -p /home/podmgr/consul/config/ /home/podmgr/consul/data/
            
            /usr/bin/curl -s -H 'X-Consul-Token: e95b599e-166e-7d80-08ad-aee76e7ddf19' -X GET -k https://consul.infra.sololab/v1/kv/config/client | \
              jq -r .[0].Value | \
              base64 --decode > /home/podmgr/consul/config/consul.hcl
            
            /usr/bin/curl -s -H 'X-Consul-Token: e95b599e-166e-7d80-08ad-aee76e7ddf19' \
              -X GET -k https://consul.infra.sololab/v1/kv/config/systemd | \
              jq -r .[0].Value | \
              base64 --decode > /home/podmgr/.config/systemd/user/consul.service

            systemctl daemon-reload --user

            systemctl enable --now --user consul
            