# code: language=ansible
# cd "$(git rev-parse --show-toplevel)\AnsibleWorkShop\runner"
# $private_data_dir = "/tmp/private"
# podman run --rm --userns=keep-id `
#   --dns 192.168.255.10 `
#   -v ./:$private_data_dir `
#   -e RUNNER_PLAYBOOK=./debug/Invoke-ConsulRequest.yml `
#   -e ANSIBLE_DISPLAY_SKIPPED_HOSTS=False `
#   localhost/ansible-ee-aio-new `
#   bash -c "ansible-runner run $private_data_dir -vv"
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: consul service
      community.general.consul:
        host: consul.infra.sololab
        port: 443
        scheme: https
        validate_certs: false
        token: e95b599e-166e-7d80-08ad-aee76e7ddf19
        service_name: ipa
        service_address: 192.168.255.10
        service_port: 443
        tcp: ipa.infra.sololab:443
        interval: 2m
        state: present
        tags:
          - traefik.enable=true
      when: false
    
    - name: consul kv
      community.general.consul_kv:
        host: consul.infra.sololab
        port: 443
        scheme: https
        validate_certs: false
        token: e95b599e-166e-7d80-08ad-aee76e7ddf19
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      loop:
        - key: config/client_dev
          # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_advanced_syntax.html#advanced-playbook-syntax
          value: !unsafe |
            bind_addr = "{{ GetInterfaceIP `eth0` }}"
            datacenter = "dc1"
            data_dir = "/home/podmgr/consul/data"
            encrypt = "qDOPBEr+/oUVeOFQOnVypxwDaHzLrD+lvjo5vCEBbZ0="
            node_name = "client_dev"
            retry_join = [
              "consul.infra.sololab"
            ]

        - key: config/systemd
          value: |
            [Unit]
            Description="HashiCorp Consul - A service mesh solution"
            Documentation=https://www.consul.io/
            Wants=network-online.target
            After=network-online.target
            ConditionFileNotEmpty=/home/podmgr/consul/config/consul.hcl

            [Service]
            EnvironmentFile=-/home/podmgr/consul/config/consul.env
            ExecStart=/usr/bin/consul agent -config-dir=/home/podmgr/consul/config/
            ExecReload=/bin/kill --signal HUP $MAINPID
            KillMode=process
            KillSignal=SIGTERM
            Restart=on-failure
            LimitNOFILE=65536

            [Install]
            WantedBy=default.target
