# https://github.com/grafana/loki/blob/main/examples/getting-started/docker-compose.yaml#L59
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mc
# spec:
#   resources:
#     requests:
#       storage: 20Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio
data:
  # https://min.io/docs/minio/linux/operations/network-encryption.html#enabling-tls
  sololab.crt: |
    {{ Root_CA_Cert | indent(width=4) }}

---
apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    name: minio
spec:
  initContainers:
  #   - name: mc
  #     image: quay.io/minio/mc:latest
  #     imagePullPolicy: IfNotPresent
  #     command:
  #       - '/bin/sh'
  #       - '-c'
  #     args:
  #       - 'cp /usr/bin/mc /mnt/bin/mc'
  #     volumeMounts:
  #       - name: mc
  #         mountPath: /mnt/bin/
  
  # https://varlogdiego.com/kubernetes-wait-until-another-pod-is-ready
    - name: wait-for-idp
      image: docker.io/curlimages/curl:8.00.1
      imagePullPolicy: IfNotPresent
      command: 
        - "/bin/sh"
        - "-c"
      args: 
        - "while [ $(curl -sw '200' -k -x GET https://keycloak.infra.sololab/realms/sololab/.well-known/openid-configuration -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the keycloak...'; done"
  containers:
    - name: minio
      image: quay.io/minio/minio:RELEASE.2023-04-07T05-28-58Z
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        # https://blog.csdn.net/weixin_45395031/article/details/119273223
        # https://github.com/minio/minio/tree/master/docs/config#credentials
        - name: MINIO_ROOT_USER # MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_ROOT_PASSWORD # MINIO_SECRET_KEY
          value: password
        # https://github.com/minio/minio/blob/master/docs/metrics/prometheus/README.md#2-configure-authentication-type-for-prometheus-metrics
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        # https://github.com/minio/minio/blob/a6057c35cc05eba06c531e7c2f833e0b0880614f/cmd/common-main.go#L727
        - name: MINIO_UPDATE
          value: off
        # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_BROWSER_REDIRECT_URL
        # should match with the url config
        - name: MINIO_BROWSER_REDIRECT_URL
          value: https://minio.infra.sololab/console/

        # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#openid-identity-management
        - name:  MINIO_IDENTITY_OPENID_CONFIG_URL
          value: https://keycloak.infra.sololab/realms/sololab/.well-known/openid-configuration
          
        - name:  MINIO_IDENTITY_OPENID_CLIENT_ID
          value: minio
          
        - name:  MINIO_IDENTITY_OPENID_CLIENT_SECRET
          value: z2KqVuwXQ28vseV5ITk8st16r5fZfoQ8
          
        - name:  MINIO_IDENTITY_OPENID_CLAIM_NAME
          value: policy
          
        - name:  MINIO_IDENTITY_OPENID_SCOPES
          value: openid,email
          
      # https://blog.csdn.net/fly910905/article/details/104706105
      # https://github.com/minio/minio/blob/master/Dockerfile
      args:
        # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#id1
        - 'server'
        # - '--address'
        # - ':9000'
        # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#minio.server.-console-address
        - '--console-address'
        - ':9001'
        # https://min.io/docs/minio/linux/operations/network-encryption.html#enabling-tls
        - '--certs-dir'
        - '/mnt/certs'
        # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#minio.server.DIRECTORIES
        - '/data'

      # https://github.com/minio/console/issues/2681
      # startupProbe:
      #   exec:
      #     command:
      #       - update-ca-trust
      #   successThreshold: 1
      #   initialDelaySeconds: 0
      #   periodSeconds: 1
      # https://min.io/docs/minio/linux/operations/monitoring/healthcheck-probe.html#node-liveness
      livenessProbe:
        httpGet:
          path: /minio/health/live
          port: 9000
          scheme: HTTP
        initialDelaySeconds: 120
        periodSeconds: 1800
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      volumeMounts:
        # - name: mc
        #   mountPath: /mnt/bin/
        - name: minio
          mountPath: /data
        # https://github.com/minio/console/issues/2681
        # - name: sololab.crt
        #   mountPath: /etc/pki/ca-trust/source/anchors/sololab.crt
        #   subPath: sololab.crt
        - name: sololab.crt
          mountPath: /mnt/certs/CAs/sololab.crt
          subPath: sololab.crt
  volumes:
    # - name: mc
    #   persistentVolumeClaim:
    #     claimName: mc
    - name: minio
      persistentVolumeClaim:
        claimName: minio
    - name: sololab.crt
      configMap:
        name: minio
        items:
          - key: sololab.crt
            path: sololab.crt
  restartPolicy: Never