# https://github.com/grafana/loki/blob/main/examples/getting-started/docker-compose.yaml#L59
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mc
# spec:
#   resources:
#     requests:
#       storage: 20Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio
data:
  # https://min.io/docs/minio/linux/operations/network-encryption.html#enabling-tls
  sololab.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEkTCCAvmgAwIBAgIBATANBgkqhkiG9w0BAQsFADA4MRYwFAYDVQQKDA1JTkZSQS5TT0xPTEFC
    MR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjMwMjIzMDkwOTQ4WhcNNDMwMjIz
    MDkwOTQ4WjA4MRYwFAYDVQQKDA1JTkZSQS5TT0xPTEFCMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBB
    dXRob3JpdHkwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQC4QiEj78sKzN87dpnS67Lq
    c3s+af6QfW1WlKqIg71WY8e6voZ2SaHXscAOXwLOJ0NmMRaeJfwYeK1oSCftqOOxlGfoR44m+IKO
    lxcIqyDCLc11EEb3I3UUY/f+l+hJcu0ZeWYJYh9/JwhF+s1IUM+jDcvUIr65JOLnsPFfpq2e+eHR
    ZKpcPHpr951SNkO+zMpyjFx4bbcOQBaKWzgls1ZONf5n8P/eoaFrG9Csy7F6zbTrFh4Ud23vvP/G
    /Utsy2Y/B5XjVEOPSNiH1Hm4m20P7stfeDZ3MUm0C/dCH+uBiDgSdGXQMlhMJSgQ9aDQSsBUKI4y
    bXFC3LOPjyTa8iLyz1edH7cP3HoYKFxYEN0XQlVUJLJ8UqHOhtCebx0ibPDAYHlIvIYtfDx4+l2u
    Zvq9fZYlaXdmyL1Wx/gzCnXsMY+fG5l4IQygbcJquKurk4E+ODBh0PwzN/cT+giDykQvlXDfqTa2
    gaBhMNm/PfXCPN1EivxQ9ZSWf+vcNqa3G38CAwEAAaOBpTCBojAfBgNVHSMEGDAWgBTo99wAw9Dr
    M4GCSq2cCf34/zB7LzAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQU
    6PfcAMPQ6zOBgkqtnAn9+P8wey8wPwYIKwYBBQUHAQEEMzAxMC8GCCsGAQUFBzABhiNodHRwOi8v
    aXBhLWNhLmluZnJhLnNvbG9sYWIvY2Evb2NzcDANBgkqhkiG9w0BAQsFAAOCAYEASaN38g8nM0C3
    yToA9olrhitQ6G5qssFFNtPY+IEpleP/SIGi7JgnnmPNeZonplFhf0qh9H/oJT3degPKrU0ccmNu
    4+35mQQ4WBdrqaCBNFImnZ0N5vBS5kvp6fmPeWp6OwhfDGRaItqIo2iJKCR9rfI74mD69JpVNfrB
    q65iIR+OJ6XrE0m/s7hlUOgYmu7Lbm85BIicRqYxe69jlohL5RIIxl/ikbZWeuhx2Yy0p83HA7hN
    DIMmf7ZvscXXYsFWFBLN70D9tdQKoy6EfyjGx/tL/jFamJuKTRyhPK+4E50MCLESVCj5+cG6Eydx
    DxDtZCeA1hs13sRK3v+wYS82DA9QvlRdAzUQjgkDt8q2ZwfvDDJ2SvZsXndFw65yHNjNdQTrXE36
    IN4oqTqoDvFDCvHZZqrtBCSV4nO1I6lc1F0ZbKYZXrMW1Rzww6DlrTf4k3OngQWuyBWoZdfUhoI0
    tdcDz5OEODZ6ynHurr0QGmCew/+gFkm/BtGIYom4S3pA
    -----END CERTIFICATE-----

---
apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    name: minio
spec:
  initContainers:
  #   - name: mc
  #     image: quay.io/minio/mc:latest
  #     imagePullPolicy: IfNotPresent
  #     command:
  #       - '/bin/sh'
  #       - '-c'
  #     args:
  #       - 'cp /usr/bin/mc /mnt/bin/mc'
  #     volumeMounts:
  #       - name: mc
  #         mountPath: /mnt/bin/
  
  # https://varlogdiego.com/kubernetes-wait-until-another-pod-is-ready
    - name: wait-for-keycloak
      image: docker.io/curlimages/curl:8.00.1
      imagePullPolicy: IfNotPresent
      command: 
        - "/bin/sh"
        - "-c"
      args: 
        - "while [ $(curl -sw '200' -k -x GET https://keycloak.infra.sololab/realms/freeipa-realm/.well-known/openid-configuration -o /dev/null) -ne 200 ]; do sleep 5; echo 'Waiting for the keycloak...'; done"
  containers:
    - name: minio
      image: quay.io/minio/minio:RELEASE.2023-03-24T21-41-23Z
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      env:
        # https://blog.csdn.net/weixin_45395031/article/details/119273223
        # https://github.com/minio/minio/tree/master/docs/config#credentials
        - name: MINIO_ROOT_USER # MINIO_ACCESS_KEY
          value: minio
        - name: MINIO_ROOT_PASSWORD # MINIO_SECRET_KEY
          value: password
        # https://github.com/minio/minio/blob/master/docs/metrics/prometheus/README.md#2-configure-authentication-type-for-prometheus-metrics
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: public
        # https://github.com/minio/minio/blob/a6057c35cc05eba06c531e7c2f833e0b0880614f/cmd/common-main.go#L727
        - name: MINIO_UPDATE
          value: off
        # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#envvar.MINIO_BROWSER_REDIRECT_URL
        # should match with the url config
        - name: MINIO_BROWSER_REDIRECT_URL
          value: https://minio.infra.sololab/console/
      # https://blog.csdn.net/fly910905/article/details/104706105
      # https://github.com/minio/minio/blob/master/Dockerfile
      args:
        # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#id1
        - 'server'
        # - '--address'
        # - ':9000'
        # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#minio.server.-console-address
        - '--console-address'
        - ':9001'
        # https://min.io/docs/minio/linux/operations/network-encryption.html#enabling-tls
        - '--certs-dir'
        - '/mnt/certs'
        # https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#minio.server.DIRECTORIES
        - '/data'

      # https://github.com/minio/console/issues/2681
      startupProbe:
        exec:
          command:
            - update-ca-trust
        successThreshold: 1
        initialDelaySeconds: 0
        periodSeconds: 1
      # https://min.io/docs/minio/linux/operations/monitoring/healthcheck-probe.html#node-liveness
      livenessProbe:
        httpGet:
          path: /minio/health/live
          port: 9000
          scheme: HTTP
        initialDelaySeconds: 120
        periodSeconds: 1800
        timeoutSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      volumeMounts:
        # - name: mc
        #   mountPath: /mnt/bin/
        - name: minio
          mountPath: /data
        # https://github.com/minio/console/issues/2681
        - name: sololab.crt
          mountPath: /etc/pki/ca-trust/source/anchors/sololab.crt
          subPath: sololab.crt
        - name: sololab.crt
          mountPath: /mnt/certs/CAs/sololab.crt
          subPath: sololab.crt
  volumes:
    # - name: mc
    #   persistentVolumeClaim:
    #     claimName: mc
    - name: minio
      persistentVolumeClaim:
        claimName: minio
    - name: sololab.crt
      configMap:
        name: minio
        items:
          - key: sololab.crt
            path: sololab.crt
  restartPolicy: Never