apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul
data:
  # https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/server-config-configmap.yaml#L17
  # https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml
  # https://developer.hashicorp.com/consul/docs/agent/config/cli-flags#_datacenter
  # https://developer.hashicorp.com/consul/docs/agent/config/cli-flags#_domain
  # https://developer.hashicorp.com/consul/docs/agent/config/cli-flags#_data_dir
  # https://developer.hashicorp.com/consul/docs/agent/config/cli-flags#_server
  # https://developer.hashicorp.com/consul/docs/agent/config/config-files
  config.json: |
    {
        "datacenter": "localhost",
        "domain":"consul",
        "data_dir": "/consul/data",
        "log_level": "DEBUG",
        "server": true,
        "ui": true,
        "bootstrap_expect":1,
        "addresses": {
            "http":"0.0.0.0"
        },
        "retry_join": ["127.0.0.1"],
        "ports": {
          "server":8300,
          "serf_lan":8301,
          "http":8500,
          "dns":8600
        },
        "serf_lan":"0.0.0.0"
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: consul
  labels:
    name: consul
spec:
  # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html
  # https://github.com/docker-library/docs/tree/master/consul
  # https://github.com/hashicorp/docker-consul
  containers:
    - name: consul
      image: docker.io/hashicorp/consul:latest
      # env:
      #   - name: TZ
      #     value: Asia/Shanghai
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      ports:
        - name: server
          containerPort: 8300
        - name: serf_lan
          containerPort: 8301
        - name: web
          containerPort: 8500
        - name: dns
          containerPort: 8600
          protocol: UDP
      # https://developer.hashicorp.com/consul/tutorials/day-0/docker-container-agents#configure-and-run-a-consul-server
      command:
        - consul
      args:
        - agent
        - -config-file=/consul/config/config.json
      volumeMounts:
        - name: consul_config
          mountPath: /consul/config/config.json
          subPath: config.json
        - name: consul_data
          mountPath: /consul/data
  volumes:
    - name: consul_config
      # https://kubernetes.io/docs/concepts/storage/volumes/#configmap
      configMap:
        name: consul
        items:
          - key: config.json
            path: config.json
    - name: consul_data
      persistentVolumeClaim:
        claimName: consul
  restartPolicy: Never
