# code: language=ansible
---
- name: Delegate container related permission to non-root user (systemd)
  become: true
  when: 
    - ansible_service_mgr == "systemd"
  block:
    # Detect files for all user cgroup delegate
    - name: Detect /etc/systemd/system/user@.service.d/delegate.conf
      when:
        - definitive_cgroups_delegation.all_users.state != "skipped"
      ansible.builtin.stat:
        path: /etc/systemd/system/user@.service.d/delegate.conf
      register: systemd_all_users_delegate_conf
    
    # Present block for all user cgroup delegate
    - name: Present cgroup delegation config to all users
      when:
        - definitive_cgroups_delegation.all_users.state == "present"
      block:
        # Create files
        - name: Create /etc/systemd/system/user@.service.d/delegate.conf
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: "{{ item.state }}"
            mode: '0755'
          loop:
            # https://wiki.archlinux.org/title/Cgroups
            - path: "/etc/systemd/system/user@.service.d"
              state: directory
            - path: "/etc/systemd/system/user@.service.d/delegate.conf"
              state: touch
          when:
            - systemd_all_users_delegate_conf.stat.exists is defined
            - systemd_all_users_delegate_conf.stat.exists is false
        
        # Detect blocks
        - name: Detect systemd_cgroup_delegate_block in /etc/systemd/system/user@.service.d/delegate.conf
          ansible.builtin.blockinfile:
            path: /etc/systemd/system/user@.service.d/delegate.conf
            marker: "# {mark} {{ role_name }} systemd_cgroup_delegate"
            state: absent
          check_mode: true
          changed_when: false
          register: systemd_cgroup_delegate_block
        
        - name: Detect Delegate= line in /etc/systemd/system/user@.service.d/delegate.conf
          ansible.builtin.lineinfile:
            path: /etc/systemd/system/user@.service.d/delegate.conf
            regexp: "^Delegate="
            state: absent
          check_mode: true
          changed_when: false
          register: systemd_cgroup_delegate_line
        
        # Comment out origin one
        - name: Comment out previous [Service] and Delegate line for override in /etc/systemd/system/user@.service.d/delegate.conf
          ansible.builtin.replace:
            path: /etc/systemd/system/user@.service.d/delegate.conf 
            regexp: "{{ item }}"
            replace: '# comment by {{ role_name }} \1'
          loop:
            - '^\s*(\[Service\])'
            - '^\s*(Delegate=.*)'
          when:
            - cgroups_delegation.all_users.present_override is true
        
        # Set blocks
        - name: Set systemd service unit cgroup Delegate block for all users
          ansible.builtin.blockinfile:
            # https://wiki.archlinux.org/title/Cgroups#Controller_types
            path: /etc/systemd/system/user@.service.d/delegate.conf
            marker: "# {mark} {{ role_name }} systemd_cgroup_delegate"
            insertafter: '\[Service\]$'
            block: |
              [Service]
              Delegate={{ cgroups_delegation.all_users.resources }}
          when:
            - not (
                cgroups_delegation.all_users.present_override is false
                and not 'Block removed' in systemd_cgroup_delegate_block.msg
                and systemd_cgroup_delegate_line.found is defined
                and systemd_cgroup_delegate_line.found != 0
              )
          notify: 
            - Reload-SystemdDaemon

    # Absent block for all user cgroup delegate
    - name: Absent cgroup delegation config to all users
      when:
        - definitive_cgroups_delegation.all_users.state == "absent"
        - systemd_all_users_delegate_conf.stat.exists is defined
        - systemd_all_users_delegate_conf.stat.exists is true
      block:    
        # Remove blocks
        - name: Remove systemd_cgroup_delegate_block
          ansible.builtin.blockinfile:
            path: /etc/systemd/system/user@.service.d/delegate.conf
            marker: "# {mark} {{ role_name }} systemd_cgroup_delegate"
            state: absent
          notify: 
            - Reload-SystemdDaemon
        
        # Uncomment lines
        - name: Uncomment [Service] and Delegate line /etc/rc.conf
          ansible.builtin.replace:
            path: /etc/systemd/system/user@.service.d/delegate.conf
            regexp: "{{ item }}"
            replace: '\1'
          loop:
            - '^\s*# comment by {{ role_name }} (\[Service\])'
            - '^\s*# comment by {{ role_name }} (Delegate=.*)'


    # Detect info for per user cgroup delegate
    - name: Detect info for per user cgroup delegate
      when:
        - definitive_cgroups_delegation.per_user.state != "skipped"
      block:
        # Detect uid
        - name: Detect {{ target_user }} uid
          ansible.builtin.shell: 
            cmd: id -u
          become_user: "{{ target_user }}"
          changed_when: false
          register: target_user_uid

        # Detect files 
        # https://wiki.archlinux.org/title/Cgroups#User_delegation
        - name: Detect delegate conf state for {{ target_user }}
          ansible.builtin.stat:
            path: /etc/systemd/system/user@{{ target_user_uid.stdout }}.service.d/delegate-{{ role_name }}.conf
          register: systemd_per_users_delegate_conf
    
    # Present block for per user cgroup delegate
    - name: Present cgroup delegation config to {{ target_user }}
      when: 
        - definitive_cgroups_delegation.per_user.state == "present"
      block:
        # Create file
        - name: Create /etc/systemd/system/user@"{{ target_user_uid.stdout }}".service.d/delegate-{{ role_name }}.conf
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: "{{ item.state }}"
            mode: '0755'
          loop:
            # https://wiki.archlinux.org/title/Cgroups
            - path: "/etc/systemd/system/user@{{ target_user_uid.stdout }}.service.d"
              state: directory
            - path: "/etc/systemd/system/user@{{ target_user_uid.stdout }}.service.d/delegate-{{ role_name }}.conf"
              state: touch
          when:
            - systemd_per_users_delegate_conf.stat.exists is defined
            - systemd_per_users_delegate_conf.stat.exists is false

        # Present block
        # https://wiki.archlinux.org/title/Cgroups#Controller_types
        - name: Present delegate block for {{ target_user }}
          ansible.builtin.blockinfile:
            path: "/etc/systemd/system/user@{{ target_user_uid.stdout }}.service.d/delegate-{{ role_name }}.conf"
            marker: "# {mark} {{ role_name }} delegation"
            block: |
              [Service]
              Delegate={{ cgroups_delegation.per_user.resources }}
          notify: 
            - Reload-SystemdDaemon
    
    # Absent block for per user cgroup delegate
    - name: Absent cgroup delegation to {{ target_user }}
      when:
        - definitive_cgroups_delegation.per_user.state == "absent"
        - systemd_per_users_delegate_conf.stat.exists is defined
        - systemd_per_users_delegate_conf.stat.exists is true
      block:
      # Delete conf file
        - name: Delete /etc/systemd/system/user@"{{ target_user_uid.stdout }}".service.d/delegate-{{ role_name }}.conf
          ansible.builtin.file:
            path: "/etc/systemd/system/user@{{ target_user_uid.stdout }}.service.d/delegate-{{ role_name }}.conf"
            state: absent
          notify: 
            - Reload-SystemdDaemon
        

  # https://github.com/ahwayakchih/nobbic/blob/82509c475de075670de910f56b550709c4665e08/docs/SetupPodmanOnAlpineHost.markdown#switch-cgroups-to-v2
- name: Set cgroup resource config to all user (openrc)
  become: true
  when: 
    - ansible_service_mgr == "openrc"
  block:
    # Present block for all user cgroup delegate
    - name: Present cgroup delegation config to all users
      when:
        - definitive_cgroups_delegation.all_users.state == "present"
      block:
        # Detect blocks
        - name: Detect rc_cgroup_mode block in /etc/rc.conf
          ansible.builtin.blockinfile:
            path: /etc/rc.conf
            marker: "# {mark} {{ role_name }} rc_cgroup_mode"
            state: absent
          check_mode: true
          changed_when: false
          register: rc_cgroup_mode_block

        # Detect lines
        - name: Detect rc_cgroup_mode line in /etc/rc.conf
          ansible.builtin.lineinfile:
            path: /etc/rc.conf
            regexp: "^rc_cgroup_mode"
            state: absent
          check_mode: true
          changed_when: false
          when:
            - "not 'Block removed' in rc_cgroup_mode_block.msg"
          register: rc_cgroup_mode_line

        # Comment out origin one
        # https://www.shellhacks.com/ansible-comment-out-uncomment-lines-in-a-file/
        - name: Comment out previous rc_cgroup_mode line in /etc/rc.conf
          ansible.builtin.replace:
            path: /etc/rc.conf
            regexp: '^\s*(rc_cgroup_mode=.*)'
            replace: '# comment by {{ role_name }} \1'
          when:
            - cgroups_delegation.all_users.present_override is true

        # Set block
        - name: Set rc_cgroup_mode block
          ansible.builtin.blockinfile:
            path: /etc/rc.conf
            marker: "# {mark} {{ role_name }} rc_cgroup_mode"
            insertafter: '^#rc_cgroup_mode=(.*)'
            block: rc_cgroup_mode="unified"
            state: present
          when:
            - not (
                cgroups_delegation.all_users.present_override is false
                and not 'Block removed' in rc_cgroup_mode_block.msg
                and rc_cgroup_mode_line.found is defined
                and rc_cgroup_mode_line.found != 0
              )

    # Absent block for all user cgroup delegate
    - name: Absent cgroup delegation config to all users
      when:
        - definitive_cgroups_delegation.all_users.state == "absent"
      block:
        # remove block
        - name: Remove rc_cgroup_mode block
          ansible.builtin.blockinfile:
            path: /etc/rc.conf
            marker: "# {mark} {{ role_name }} rc_cgroup_mode"
            state: absent

        # uncomment line 
        - name: Uncomment rc_cgroup_mode line in /etc/rc.conf
          ansible.builtin.replace:
            path: /etc/rc.conf
            regexp: '^\s*# comment by {{ role_name }} (rc_cgroup_mode=.*)'
            replace: '\1'
