# code: language=ansible
---
- name: Set value in /etc/subuid
  become: yes
  block:
    - name: Detect subuid file
      ansible.builtin.stat:
        path: /etc/subuid
      register: etc_subuid

    - name: Create /etc/subuid
      ansible.builtin.file:
        path: /etc/subuid
        state: touch
        mode: u=rw,g=r,o=r
      when:
        - definitive_sub_ids.state == "present"
        - etc_subuid.stat.exists is false

    # https://stackoverflow.com/questions/29075287/ansible-insert-line-if-not-exists
    - name: Detect config in /etc/subuid for present
      ansible.builtin.lineinfile:
        path: /etc/subuid
        regexp: "^{{ target_user }}"
        state: absent
      when:
        - definitive_sub_ids.state == "present"
        - etc_subuid.stat.exists is true
      check_mode: true
      changed_when: false
      register: subuid_target

    - name: Set {{ target_user }} in /etc/subuid
      ansible.builtin.blockinfile:
        path: /etc/subuid
        marker: "# {mark} {{ role_name }} {{ target_user }}"
        block: |
          {{ sub_ids.subuid.user }}:{{ sub_ids.subuid.start_from }}:{{ sub_ids.subuid.offset }}
        state: present
      when: 
        - definitive_sub_ids.state == "present"
        - etc_subuid.stat.exists is true
        - subuid_target.found == 0

    - name: Remove {{ target_user }} in /etc/subuid
      ansible.builtin.blockinfile:
        path: /etc/subuid
        marker: "# {mark} {{ role_name }} {{ target_user }}"
        state: absent
      when: 
        - definitive_sub_ids.state == "absent"
        - etc_subuid.stat.exists is true


- name: Set value in /etc/subgid
  become: yes
  block:
    - name: Detect subgid file
      ansible.builtin.stat:
        path: /etc/subgid
      register: etc_subgid

    - name: Create /etc/subgid
      ansible.builtin.file:
        path: /etc/subgid
        state: touch
        mode: u=rw,g=r,o=r
      when:
        - definitive_sub_ids.state == "present"
        - etc_subgid.stat.exists is false

    - name: Detect config in /etc/subgid
      ansible.builtin.lineinfile:
        path: /etc/subgid
        regexp: "^{{ target_user }}"
        state: absent
      when:
        - definitive_sub_ids.state == "present"
        - etc_subgid.stat.exists is true
      check_mode: true
      changed_when: false
      register: subgid_target

    - name: Set {{ target_user }} in /etc/subgid
      ansible.builtin.blockinfile:
        path: /etc/subgid
        marker: "# {mark} {{ role_name }} {{ target_user }}"
        block: |
          {{ sub_ids.subgid.group }}:{{ sub_ids.subgid.start_from }}:{{ sub_ids.subgid.offset }}
        state: present
      when: 
        - definitive_sub_ids.state == "present"
        - etc_subgid.stat.exists is true
        - subgid_target.found == 0

    - name: Remove {{ target_user }} in /etc/subgid
      ansible.builtin.blockinfile:
        path: /etc/subgid
        marker: "# {mark} {{ role_name }} {{ target_user }}"
        state: absent
      when: 
        - definitive_sub_ids.state == "absent"
        - etc_subgid.stat.exists is true