# code: language=ansible
---
- name: Delegate container related permission to non-root user (systemd)
  when: 
    - ansible_service_mgr == "systemd"
  block:
    - name: Set cgroup delegation to all users
      become: yes
      when:
        - definitive_cgroups_delegation.all_users.skipped is false
      block:
        - name: Detect file state for all users
          ansible.builtin.stat:
            path: /etc/systemd/system/user@.service.d/delegate-{{ role_name }}.conf
          register: systemd_all_users_serviced

        - name: Create /etc/systemd/system/user@.service.d/delegate-{{ role_name }}.conf
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: "{{ item.state }}"
            mode: '0755'
          loop:
            # https://wiki.archlinux.org/title/Cgroups
            - path: "/etc/systemd/system/user@.service.d"
              state: directory
            - path: "/etc/systemd/system/user@.service.d/delegate-{{ role_name }}.conf"
              state: touch
          when:
            - systemd_all_users_serviced.stat.exists is defined
            - systemd_all_users_serviced.stat.exists is false
            - definitive_cgroups_delegation.all_users.state == "present"

        - name: Enable resources delegation for all users
          ansible.builtin.blockinfile:
            # https://wiki.archlinux.org/title/Cgroups#Controller_types
            path: "/etc/systemd/system/user@.service.d/delegate-{{ role_name }}.conf"
            marker: "# {mark} {{ role_name }} delegation"
            block: |
              [Service]
              Delegate={{ cgroups_delegation.all_users.resources }}
          when:
            - definitive_cgroups_delegation.all_users.state == "present"
          notify: 
            - Reload-SystemdDaemon

        - name: Delete /etc/systemd/system/user@.service.d/delegate-{{ role_name }}.conf
          ansible.builtin.file:
            path: "/etc/systemd/system/user@.service.d/delegate-{{ role_name }}.conf"
            state: absent
          when:
            - definitive_cgroups_delegation.all_users.state == "absent"
          notify: 
            - Reload-SystemdDaemon

    - name: Set cgroup delegation to {{ target_user }}
      become: yes
      when:
        - definitive_cgroups_delegation.per_user.skipped is false
      block:
        - name: Detect {{ target_user }} uid
          ansible.builtin.shell: 
            cmd: id -u
          become_user: "{{ target_user }}"
          register: target_user_uid
          changed_when: false

        # https://wiki.archlinux.org/title/Cgroups#User_delegation
        - name: Detect file state for {{ target_user }}
          ansible.builtin.stat:
            path: /etc/systemd/system/user@{{ target_user_uid.stdout }}.service.d/delegate-{{ role_name }}.conf
          register: systemd_per_user_serviced

        - name: Create /etc/systemd/system/user@"{{ target_user_uid.stdout }}".service.d/delegate-{{ role_name }}.conf
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: "{{ item.state }}"
            # owner: "{{ target_user }}"
            # group: "{{ target_user }}"
            mode: '0755'
          loop:
            # https://wiki.archlinux.org/title/Cgroups
            - path: "/etc/systemd/system/user@{{ target_user_uid.stdout }}.service.d"
              state: directory
            - path: "/etc/systemd/system/user@{{ target_user_uid.stdout }}.service.d/delegate-{{ role_name }}.conf"
              state: touch
          when:
            - systemd_per_user_serviced.stat.exists is defined
            - systemd_per_user_serviced.stat.exists is false
            - definitive_cgroups_delegation.per_user.state == "present"

        - name: Enable resources delegation for {{ target_user }}
          ansible.builtin.blockinfile:
            # https://wiki.archlinux.org/title/Cgroups#Controller_types
            path: "/etc/systemd/system/user@{{ target_user_uid.stdout }}.service.d/delegate-{{ role_name }}.conf"
            marker: "# {mark} {{ role_name }} delegation"
            block: |
              [Service]
              Delegate={{ cgroups_delegation.per_user.resources }}
          when:
            - definitive_cgroups_delegation.per_user.state == "present"
          notify: 
            - Reload-SystemdDaemon

        - name: Delete /etc/systemd/system/user@"{{ target_user_uid.stdout }}".service.d/delegate-{{ role_name }}.conf
          ansible.builtin.file:
            path: "/etc/systemd/system/user@{{ target_user_uid.stdout }}.service.d/delegate-{{ role_name }}.conf"
            state: absent
          when:
            - definitive_cgroups_delegation.per_user.state == "absent"
          notify: 
            - Reload-SystemdDaemon
        

  # https://github.com/ahwayakchih/nobbic/blob/82509c475de075670de910f56b550709c4665e08/docs/SetupPodmanOnAlpineHost.markdown#switch-cgroups-to-v2
- name: Set cgroup resource config to all user (openrc)
  when: 
    - ansible_service_mgr == "openrc"
    - definitive_cgroups_delegation.all_users.skipped is false
  become: yes
  block:
    - name: Detect rc_cgroup_mode config in /etc/rc.conf
      ansible.builtin.lineinfile:
        path: /etc/rc.conf
        regexp: "^rc_cgroup_mode"
        state: absent
      check_mode: yes
      changed_when: no
      register: rc_cgroup_mode_config

    - name: Delete rc_cgroup_mode config in /etc/rc.conf
      ansible.builtin.lineinfile:
        path: /etc/rc.conf
        regexp: "^rc_cgroup_mode"
        state: absent
      check_mode: false
      when:
        - cgroups_delegation.all_users.rc_conf_override is true

    - name: Set rc_cgroup_mode
      ansible.builtin.blockinfile:
        path: /etc/rc.conf
        marker: "# {mark} {{ role_name }} rc_cgroup_mode"
        insertafter: '^#rc_cgroup_mode=(.*)'
        block: rc_cgroup_mode="unified"
        state: present
      when:
        - (cgroups_delegation.all_users.rc_conf_override is true
            or rc_cgroup_mode_config.found == 0)
        - definitive_cgroups_delegation.all_users.state == "present"

    - name: Remove rc_cgroup_mode
      ansible.builtin.blockinfile:
        path: /etc/rc.conf
        marker: "# {mark} {{ role_name }} rc_cgroup_mode"
        state: absent
      when:
        - definitive_cgroups_delegation.all_users.state == "absent"


    # https://wiki.gentoo.org/wiki/OpenRC/CGroups
    - name: Detect rc_cgroup_controllers line in /etc/rc.conf
      ansible.builtin.lineinfile:
        path: /etc/rc.conf
        regexp: "^rc_cgroup_controllers"
        state: absent
      check_mode: yes
      changed_when: no
      register: rc_cgroup_controllers_config

    - name: Delete rc_cgroup_controllers line in /etc/rc.conf
      ansible.builtin.lineinfile:
        path: /etc/rc.conf
        regexp: "^rc_cgroup_controllers"
        state: absent
      check_mode: no
      when:
        - cgroups_delegation.all_users.rc_conf_override is true

    - name: Set rc_cgroup_controllers
      ansible.builtin.blockinfile:
        path: /etc/rc.conf
        marker: "# {mark} {{ role_name }} rc_cgroup_controllers"
        insertafter: '^#rc_cgroup_controllers(.*)'
        block: rc_cgroup_controllers="{{ definitive_cgroups_delegation.all_users.resources }}"
        state: present
      when:
        - ( cgroups_delegation.all_users.rc_conf_override is true
            or rc_cgroup_mode_config.found == 0 )
        - definitive_cgroups_delegation.all_users.state == "present"

    - name: Remove rc_cgroup_controllers
      ansible.builtin.blockinfile:
        path: /etc/rc.conf
        marker: "# {mark} {{ role_name }} rc_cgroup_controllers"
        state: absent
      when:
        - definitive_cgroups_delegation.all_users.state == "absent"