apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
data:
  tls.crt: tls.crt
  tls.key: tls.key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-key-pair