apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: default
---
apiVersion: v1
kind: Pod
metadata:
  name: lldap
  labels:
    name: lldap
spec:
  # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html
  # https://github.com/containers/podman/issues/7626
  containers:
    - name: lldap
      image: docker.io/nitnelave/lldap:latest
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      env:
        # - name: TZ
        #   value: Asia/Shanghai
        - name: LLDAP_JWT_SECRET
          value: REPLACE_WITH_RANDOM
        - name: LLDAP_LDAP_USER_PASS
          value: password
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: web
          containerPort: 17170
        - name: ldap
          containerPort: 3890
      volumeMounts:
        - name: lldap_data
          mountPath: /data
  volumes:
    # - name: lldap_data
    #   hostPath:
    #     path: /home/vagrant/infra/lldap/data
    #     type: Directory
    - name: lldap_data
      persistentVolumeClaim:
        claimName: lldap
  restartPolicy: Never