jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: $${jenkins_admin_user}
          name: Jenkins Admin
          password: $${jenkins_admin_password}
unclassified:
  location:
    adminAddress: null
    url: "https://${FQDN}"
