apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
data:
  traefik.yml: |
    # Static Configuration

    ## Configuration Discovery
    # https://doc.traefik.io/traefik/providers/overview/
    providers:
    # https://doc.traefik.io/traefik/providers/file/#directory
      file:
        directory: /etc/traefik/dynamic/
        watch: true

    # ref: https://www.vtulluru.com/how-to-install-traefik-as-a-container-using-docker-or-podman/
    # https://doc.traefik.io/traefik/reference/static-configuration/file/
    global:
      checkNewVersion: false
      sendAnonymousUsage: false

    ## Routing & Load Balancing
    # https://doc.traefik.io/traefik/routing/overview/
    entryPoints:
      # https://doc.traefik.io/traefik/routing/entrypoints/#entrypoints
      # https://doc.traefik.io/traefik/routing/routers/#configuration-example
      web:
        address: ":80"
        # http:
        #   redirections:
        #     entryPoint:
        #       to: websecure
        #       scheme: https
        # https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers
        forwardedHeaders:
          trustedIPs:
            - "0.0.0.0/0"
      websecure:
        address: ":443"
        forwardedHeaders:
          trustedIPs:
            - "0.0.0.0/0"

    # https://doc.traefik.io/traefik/routing/overview/#transport-configuration
    serversTransport:
      # https://doc.traefik.io/traefik/routing/overview/#rootcas
      rootCAs:
        - /etc/traefik/root_ca.crt

    ## Operations
    # https://doc.traefik.io/traefik/operations/api/
    api:
      dashboard: true

    # https://smallstep.com/docs/tutorials/acme-protocol-acme-clients#traefik
    # https://doc.traefik.io/traefik/https/acme/#certificate-resolvers
    certificatesResolvers:
      freeipa:
        acme:
          caServer: https://ipa-ca.infra.sololab/acme/directory
          email: admin@INFRA.SOLOLAB
          storage: acme.json
          httpChallenge:
            # used during the challenge
            entryPoint: web
  root_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEkTCCAvmgAwIBAgIBATANBgkqhkiG9w0BAQsFADA4MRYwFAYDVQQKDA1JTkZSQS5TT0xPTEFC
    MR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMjMwMjIzMDkwOTQ4WhcNNDMwMjIz
    MDkwOTQ4WjA4MRYwFAYDVQQKDA1JTkZSQS5TT0xPTEFCMR4wHAYDVQQDDBVDZXJ0aWZpY2F0ZSBB
    dXRob3JpdHkwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQC4QiEj78sKzN87dpnS67Lq
    c3s+af6QfW1WlKqIg71WY8e6voZ2SaHXscAOXwLOJ0NmMRaeJfwYeK1oSCftqOOxlGfoR44m+IKO
    lxcIqyDCLc11EEb3I3UUY/f+l+hJcu0ZeWYJYh9/JwhF+s1IUM+jDcvUIr65JOLnsPFfpq2e+eHR
    ZKpcPHpr951SNkO+zMpyjFx4bbcOQBaKWzgls1ZONf5n8P/eoaFrG9Csy7F6zbTrFh4Ud23vvP/G
    /Utsy2Y/B5XjVEOPSNiH1Hm4m20P7stfeDZ3MUm0C/dCH+uBiDgSdGXQMlhMJSgQ9aDQSsBUKI4y
    bXFC3LOPjyTa8iLyz1edH7cP3HoYKFxYEN0XQlVUJLJ8UqHOhtCebx0ibPDAYHlIvIYtfDx4+l2u
    Zvq9fZYlaXdmyL1Wx/gzCnXsMY+fG5l4IQygbcJquKurk4E+ODBh0PwzN/cT+giDykQvlXDfqTa2
    gaBhMNm/PfXCPN1EivxQ9ZSWf+vcNqa3G38CAwEAAaOBpTCBojAfBgNVHSMEGDAWgBTo99wAw9Dr
    M4GCSq2cCf34/zB7LzAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQU
    6PfcAMPQ6zOBgkqtnAn9+P8wey8wPwYIKwYBBQUHAQEEMzAxMC8GCCsGAQUFBzABhiNodHRwOi8v
    aXBhLWNhLmluZnJhLnNvbG9sYWIvY2Evb2NzcDANBgkqhkiG9w0BAQsFAAOCAYEASaN38g8nM0C3
    yToA9olrhitQ6G5qssFFNtPY+IEpleP/SIGi7JgnnmPNeZonplFhf0qh9H/oJT3degPKrU0ccmNu
    4+35mQQ4WBdrqaCBNFImnZ0N5vBS5kvp6fmPeWp6OwhfDGRaItqIo2iJKCR9rfI74mD69JpVNfrB
    q65iIR+OJ6XrE0m/s7hlUOgYmu7Lbm85BIicRqYxe69jlohL5RIIxl/ikbZWeuhx2Yy0p83HA7hN
    DIMmf7ZvscXXYsFWFBLN70D9tdQKoy6EfyjGx/tL/jFamJuKTRyhPK+4E50MCLESVCj5+cG6Eydx
    DxDtZCeA1hs13sRK3v+wYS82DA9QvlRdAzUQjgkDt8q2ZwfvDDJ2SvZsXndFw65yHNjNdQTrXE36
    IN4oqTqoDvFDCvHZZqrtBCSV4nO1I6lc1F0ZbKYZXrMW1Rzww6DlrTf4k3OngQWuyBWoZdfUhoI0
    tdcDz5OEODZ6ynHurr0QGmCew/+gFkm/BtGIYom4S3pA
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Pod
metadata:
  name: traefik
  labels:
    name: traefik
spec:
  # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html
  # https://www.traefik.org/page/Docker#traefik_server_containers
  containers:
    - name: traefik
      image: docker.io/library/traefik:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      ports:
        # https://doc.traefik.io/traefik/getting-started/install-traefik/#use-the-official-docker-image
        - name: http
          containerPort: 80
          hostIP: 192.168.255.32
          hostPort: 80
        - name: https
          containerPort: 443
          hostIP: 192.168.255.32
          hostPort: 443
      env:
        # https://smallstep.com/docs/tutorials/acme-protocol-acme-clients#traefik
        - name: LEGO_CA_CERTIFICATES
          value: /etc/traefik/root_ca.crt
      volumeMounts:
        # https://doc.traefik.io/traefik/getting-started/configuration-overview/#configuration-file
        - name: traefik.yml
          mountPath: /etc/traefik/traefik.yml
          subPath: traefik.yml
        - name: root_ca.crt
          mountPath: /etc/traefik/root_ca.crt
          subPath: root_ca.crt
        - name: fileProvider
          mountPath: /etc/traefik/dynamic/
  volumes:
    - name: traefik.yml
      # https://kubernetes.io/docs/concepts/storage/volumes/#configmap
      configMap:
        name: traefik
        items:
          - key: traefik.yml
            path: traefik.yml
    - name: root_ca.crt
      configMap:
        name: traefik
        items:
          - key: root_ca.crt
            path: root_ca.crt
    - name: fileProvider
      hostPath:
        path: /home/vagrant/traefik/
        type: Directory
  restartPolicy: Never