apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
data:
  traefik.yml: |
    # Static Configuration

    ## Configuration Discovery
    # https://doc.traefik.io/traefik/providers/overview/
    providers:
    # https://doc.traefik.io/traefik/providers/file/#directory
      file:
        directory: /etc/traefik/dynamic/
        watch: true

    # ref: https://www.vtulluru.com/how-to-install-traefik-as-a-container-using-docker-or-podman/
    # https://doc.traefik.io/traefik/reference/static-configuration/file/
    global:
      checkNewVersion: false
      sendAnonymousUsage: false

    ## Routing & Load Balancing
    # https://doc.traefik.io/traefik/routing/overview/
    entryPoints:
      # https://doc.traefik.io/traefik/routing/entrypoints/#entrypoints
      # https://doc.traefik.io/traefik/routing/routers/#configuration-example
      web:
        address: ":80"
        # http:
        #   redirections:
        #     entryPoint:
        #       to: websecure
        #       scheme: https
        # https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers
        forwardedHeaders:
          trustedIPs:
            - "0.0.0.0/0"
      websecure:
        address: ":443"
        forwardedHeaders:
          trustedIPs:
            - "0.0.0.0/0"

    # https://doc.traefik.io/traefik/routing/overview/#transport-configuration
    serversTransport:
      # https://doc.traefik.io/traefik/routing/overview/#rootcas
      rootCAs:
        - /etc/traefik/root_ca.crt

    ## Operations
    # https://doc.traefik.io/traefik/operations/api/
    api:
      dashboard: true

    # https://smallstep.com/docs/tutorials/acme-protocol-acme-clients#traefik
    # https://doc.traefik.io/traefik/https/acme/#certificate-resolvers
    certificatesResolvers:
      freeipa:
        acme:
          caServer: https://ipa-ca.infra.sololab/acme/directory
          email: admin@INFRA.SOLOLAB
          storage: /mnt/acmeStorage/acme.json
          httpChallenge:
            # used during the challenge
            entryPoint: web
  root_ca.crt: |
    -----BEGIN CERTIFICATE-----
    {{ Root_CA_Cert.json.result.result.certificate | indent(width=4) }}
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Pod
metadata:
  name: traefik
  labels:
    name: traefik
spec:
  # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html
  # https://www.traefik.org/page/Docker#traefik_server_containers
  containers:
    - name: traefik
      image: docker.io/library/traefik:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      ports:
        # https://doc.traefik.io/traefik/getting-started/install-traefik/#use-the-official-docker-image
        - name: http
          containerPort: 80
          hostIP: 192.168.255.32
          hostPort: 80
        - name: https
          containerPort: 443
          hostIP: 192.168.255.32
          hostPort: 443
      env:
        # https://smallstep.com/docs/tutorials/acme-protocol-acme-clients#traefik
        - name: LEGO_CA_CERTIFICATES
          value: /etc/traefik/root_ca.crt
      volumeMounts:
        # https://doc.traefik.io/traefik/getting-started/configuration-overview/#configuration-file
        - name: traefik.yml
          mountPath: /etc/traefik/traefik.yml
          subPath: traefik.yml
        - name: root_ca.crt
          mountPath: /etc/traefik/root_ca.crt
          subPath: root_ca.crt
        - name: fileProvider
          mountPath: /etc/traefik/dynamic/
        - name: acmeStorage
          mountPath: /mnt/acmeStorage
  volumes:
    - name: traefik.yml
      # https://kubernetes.io/docs/concepts/storage/volumes/#configmap
      configMap:
        name: traefik
        items:
          - key: traefik.yml
            path: traefik.yml
    - name: root_ca.crt
      configMap:
        name: traefik
        items:
          - key: root_ca.crt
            path: root_ca.crt
    - name: fileProvider
      hostPath:
        path: /home/vagrant/traefik/
        type: Directory
    - name: acmeStorage
      persistentVolumeClaim:
        claimName: traefik
  restartPolicy: Never