apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
data:
  traefik.yml: |
    # Static Configuration

    ## Configuration Discovery
    # https://doc.traefik.io/traefik/providers/overview/
    providers:
    # https://doc.traefik.io/traefik/providers/file/#directory
      file:
        directory: /etc/traefik/dynamic/
        watch: true

    # ref: https://www.vtulluru.com/how-to-install-traefik-as-a-container-using-docker-or-podman/
    # https://doc.traefik.io/traefik/reference/static-configuration/file/
    global:
      checkNewVersion: false
      sendAnonymousUsage: false

    ## Routing & Load Balancing
    # https://doc.traefik.io/traefik/routing/overview/
    entryPoints:
      # https://doc.traefik.io/traefik/routing/entrypoints/#entrypoints
      # https://doc.traefik.io/traefik/routing/routers/#configuration-example
      web:
        address: ":80"
        # https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers
        forwardedHeaders:
          trustedIPs:
            - "0.0.0.0/0"
      # https://community.traefik.io/t/lets-encrypt-x509-certificate-signed-by-unknown-authority/11112/1
      websecure:
        address: ":443"
        # https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers
        # https://www.bboy.app/2020/04/16/traefik%E5%90%8E%E7%AB%AF%E5%BA%94%E7%94%A8%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E7%9C%9F%E5%AE%9Eip/
        forwardedHeaders:
          trustedIPs:
            - "0.0.0.0/0"

    # https://doc.traefik.io/traefik/routing/overview/#transport-configuration
    serversTransport:
    #   # https://doc.traefik.io/traefik/routing/overview/#rootcas
    #   rootCAs:
    #     - /etc/traefik/root_ca.crt

    ## Operations
    # https://doc.traefik.io/traefik/operations/api/
    api:
      dashboard: true

    # https://smallstep.com/docs/tutorials/acme-protocol-acme-clients#traefik
    # https://doc.traefik.io/traefik/https/acme/#certificate-resolvers
    certificatesResolvers:
      acmeResolver:
        acme:
          caServer: {{ Traefik_ACME_URL | default('https://acme-v02.api.letsencrypt.org/directory') }}
          email: {{ Traefik_ACME_email | default('')}}
          storage: /mnt/acmeStorage/acme.json
          httpChallenge:
            # used during the challenge
            entryPoint: web
  # root_ca.crt: |
  #   {#{{ Root_CA_Cert | indent(width=4) }}#}

---
apiVersion: v1
kind: Pod
metadata:
  name: traefik
  labels:
    name: traefik
spec:
  # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html
  # https://www.traefik.org/page/Docker#traefik_server_containers
  containers:
    - name: traefik
      image: "{{ Traefik_container_image }}"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      ports:
        # https://doc.traefik.io/traefik/getting-started/install-traefik/#use-the-official-docker-image
        - name: http
          containerPort: 80
          # hostIP: 192.168.255.32
          hostPort: 80
        - name: https
          containerPort: 443
          # hostIP: 192.168.255.32
          hostPort: 443
      env:
        # https://smallstep.com/docs/tutorials/acme-protocol-acme-clients/index.html#traefik
        #   - name: LEGO_CA_CERTIFICATES
        #     value: /etc/traefik/root_ca.crt
        # https://community.traefik.io/t/lets-encrypt-x509-certificate-signed-by-unknown-authority/11112/15
        # https://github.com/go-acme/lego/blob/bc4b57accc090b9c61bde051c99fcb14e952f6e6/lego/client_config.go#L18-L28
        - name: LEGO_CA_SYSTEM_CERT_POOL
          value: "true"
      volumeMounts:
        # https://doc.traefik.io/traefik/getting-started/configuration-overview/#configuration-file
        - name: traefik.yml
          mountPath: /etc/traefik/traefik.yml
          subPath: traefik.yml
        # - name: root_ca.crt
        #   mountPath: /etc/traefik/root_ca.crt
        #   subPath: root_ca.crt
        - name: fileProvider
          mountPath: /etc/traefik/dynamic/
        - name: acmeStorage
          mountPath: /mnt/acmeStorage
  volumes:
    - name: traefik.yml
      # https://kubernetes.io/docs/concepts/storage/volumes/#configmap
      configMap:
        name: traefik
        items:
          - key: traefik.yml
            path: traefik.yml
    # - name: root_ca.crt
    #   configMap:
    #     name: traefik
    #     items:
    #       - key: root_ca.crt
    #         path: root_ca.crt
    - name: fileProvider
      hostPath:
        path: /home/{{ ansible_user }}/traefik/
        type: Directory
    - name: acmeStorage
      persistentVolumeClaim:
        claimName: traefik
  restartPolicy: Never
