apiVersion: v1
kind: Pod
metadata:
  name: traefik
  labels:
    name: traefik
spec:
  # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html
  # https://www.traefik.org/page/Docker#traefik_server_containers
  containers:
    - name: traefik
      image: docker.io/library/traefik:latest
      env:
        - name: TZ
          value: Asia/Shanghai
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
      ports:
        # https://doc.traefik.io/traefik/getting-started/install-traefik/#use-the-official-docker-image
        - name: http
          containerPort: 80
          hostPort: 80
        - name: "8080"
          containerPort: 8080
          hostPort: 8080

      volumeMounts:
        # https://doc.traefik.io/traefik/getting-started/configuration-overview/#configuration-file
        - name: traefik
          mountPath: /etc/traefik/ #config.json
          # subPath: config.json
  volumes:
    - name: traefik
      # https://kubernetes.io/docs/concepts/storage/volumes/#configmap
      configMap:
        name: traefik
        items:
          - key: traefik.yml
            path: traefik.yml
  restartPolicy: OnFailure