# https://min.io/docs/minio/linux/reference/minio-server/minio-server.html#minio.server.DIRECTORIES
MINIO_OPTS='--console-address "192.168.255.2:9001"'
MINIO_VOLUMES="/mnt/data/minio"
# https://min.io/docs/minio/linux/reference/minio-server/settings/console.html#server-url
MINIO_SERVER_URL="http://192.168.255.2:9000"