---
- name: Install Dex
  block:
    - name: Add dex chart repo
      kubernetes.core.helm_repository:
        name: dex
        repo_url: "https://charts.dexidp.io"

    - name: Install Dex helm chart
      kubernetes.core.helm:
        chart_ref: dex/dex
        release_name: dex
        release_namespace: dex
        create_namespace: yes
        wait: yes
        values_files:
          - "{{ dex_helm_values_path }}"
      register: dexHelm
      retries: 10
      until: dexHelm is not failed
    
    - name: Get dex local user name(email)
      # https://stackoverflow.com/questions/68729876/get-a-yaml-file-with-http-and-use-it-as-a-variable-in-an-ansible-playbook
      ansible.builtin.include_vars:
        file: "{{ dex_helm_values_path }}"
        name: dexValue
      when: (dexHelm is succeeded)

    - name: set fact
      ansible.builtin.set_fact: 
        user: "{{ dexValue.config.staticPasswords[0].email }}"

    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/find_module.html#ansible-collections-ansible-builtin-find-module
    - name: find all templates in directories
      ansible.builtin.find:
        paths: "{{ dex_resources_dir }}"
        file_type: file
        patterns: 'resource*'
        recurse: yes
      register: templates

    - name: Dex additional resources (RBAC for dex "local admin" user)
      kubernetes.core.k8s:
        state: present
        template: "{{ item }}"
        namespace: dex
      with_items: "{{ templates.files | map(attribute='path') }}"