apiVersion: v1
kind: Pod
metadata:
  name: pgadmin4
  labels:
    name: pgadmin4
spec:
  containers:
  - name: pgadmin4
    image: docker.io/dpage/pgadmin4:6
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - name: http
        containerPort: 80
        hostPort: 5480
    env:
      - name: PGADMIN_DEFAULT_EMAIL
        value: root@root.com
      - name: PGADMIN_DEFAULT_PASSWORD
        value: root
      - name: PGADMIN_LISTEN_ADDRESS
        value: "0.0.0.0"
      - name: PGADMIN_LISTEN_PORT
        value: "80"
      # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
      # https://www.pgadmin.org/docs/pgadmin4/latest/ldap.html
      # https://github.com/DipayanP007/strimzi-kafka-debezium/blob/adb98024d25fc2cfe1843e63720567e425f276c6/charts/postgres/pgadmin4/examples/enable-ldap-integration.yaml
      - name: PGADMIN_CONFIG_AUTHENTICATION_SOURCES
        value: "['ldap', 'internal']"
      - name: PGADMIN_CONFIG_LDAP_SERVER_URI
        value: "'ldap://freeipa:389'"
      - name: PGADMIN_CONFIG_LDAP_USERNAME_ATTRIBUTE
        value: "'uid'"
      - name: PGADMIN_CONFIG_LDAP_SEARCH_BASE_DN
        value: "'cn=users,cn=accounts,dc=infra,dc=sololab'"
      - name: PGADMIN_CONFIG_LDAP_SEARCH_FILTER
        value: "'(objectclass=person)'"
      - name: PGADMIN_CONFIG_LDAP_BASE_DN
        value: "'cn=users,cn=accounts,dc=infra,dc=sololab'"
      - name: PGADMIN_CONFIG_LDAP_BIND_USER
        value: "'uid=system,cn=sysaccounts,cn=etc,dc=infra,dc=sololab'"
      - name: PGADMIN_CONFIG_LDAP_BIND_PASSWORD
        value: "'P@ssw0rd'"
    volumeMounts:
      - name: pgadmin4_data
        mountPath: /var/lib/pgadmin
  volumes:
    - name: pgadmin4_data
      hostPath:
        path: /home/vagrant/infra/pgadmin4/data
        type: Directory
  restartPolicy: Never