# Dynamic Configuration
http:
  routers:
    pgadmin4:
      rule: Host(`pgadmin4.infra.sololab`)
      service: pgadmin4
      # https://www.teanote.pub/archives/247
      # https://doc.traefik.io/traefik/routing/routers/#tls
      # will terminate the TLS request
      tls: 
        certResolver: freeipa
  services:
    pgadmin4:
      loadBalancer:
        servers:
          - url: "http://pgadmin4"