# Dynamic Configuration
http:
  routers:
    freeipa:
      rule: Host(`ipa.infra.sololab`)
      # rule: PathPrefix(`/api`) || PathPrefix(`/dashboard`)
      # entryPoints: 
      #   - websecure
      # middlewares:
      #   - subpath-stripprefixregex
      service: freeipa
      tls: true
  # middlewares:
  #   subpath-stripprefixregex:
  #     # https://doc.traefik.io/traefik/middlewares/http/stripprefixregex/
  #     stripPrefixRegex:
  #       regex:
  #         - "/sub-[a-zA-Z0-9]{1,30}"
  services:
    freeipa:
      loadBalancer:
        servers:
          - url: "https://freeipa/"
        serversTransport: freeipa
        passHostHeader: true
        sticky:
          cookie: 
            name: my_sticky_cookie_name
            secure: true
            httpOnly: true
  serversTransports:
    freeipa:
      insecureSkipVerify: true

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/dynamic/sololab_freeipa.crt
        keyFile: /etc/traefik/dynamic/sololab_freeipa.key

# https://doc.traefik.io/traefik/routing/services/#configuring-tcp-services
# https://github.com/Binsabbar/freeipa-cluster/blob/8c557a5028b3cfb439e49e2096532f92481bae96/edgeRouter/routes.yml
# tcp:
#   routers:
#     freeipa:
#       rule: "HostSNI(`ipa.infra.sololab`)"
#       entryPoints: 
#         - websecure
#       service: freeipa
#       tls: 
#         passthrough: true
#   services:
#     freeipa:
#       loadBalancer:
#         servers:
#           - address: "freeipa:443"