# code: language=ansible
---
- name: Confirm-KubeConfig
  block:
    - name: Get k8s_cluster_info
      kubernetes.core.k8s_cluster_info:
        kubeconfig: "{{ kubeconfig_path }}"
        context: default
      register: cluster_info

    - name: output info
      debug:
        msg: "{{ cluster_info.connection }}"