# code: language=ansible
---
- name: Set CoreDNS
  block:
    - name: find all templates in directories
      ansible.builtin.find:
        paths: "{{ coreDNS_resources_dir }}"
        file_type: file
        patterns: 'resource*'
        recurse: yes
      register: templates

    - name: apply CoreDNS additional resources (DNS record)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        template: "{{ item }}"
        namespace: kube-system
      with_items: "{{ templates.files | map(attribute='path') }}"