repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  # - name: incubator
  #   url: https://charts.helm.sh/incubator
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: dex
    url: https://charts.dexidp.io
  - name: fydrah-stable
    url: https://storage.googleapis.com/loginapp-releases/charts/
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  # - name: longhorn
  #   url: https://charts.longhorn.io
  # - name: puckpuck
  #   url: https://puckpuck.github.io/helm-charts
  # - name: bitnami
  #   url: https://charts.bitnami.com/bitnami

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    wait: true
    values:
    - ../cert-manager/values.yaml

  # https://github.com/roboll/helmfile/issues/1337
  # https://github.com/roboll/helmfile/issues/1682
  - name: cert-manager-issuer
    chart: ../cert-manager/ca-issuer
    namespace: cert-manager
    needs:
    - cert-manager/cert-manager
    hooks:
    - events:
        - presync
      showlogs: true
      command: "sh"
      args: 
      - "../cert-manager/Set-CAKeyPair.sh"

  - name: traefik
    chart: traefik/traefik
    namespace: traefik
    values:
    - ../traefik/values.yaml

  - name: traefik-addition-resources
    chart: ../traefik/addition-resources
    namespace: traefik
    needs: 
    - cert-manager/cert-manager
    - cert-manager/cert-manager-issuer
    - traefik/traefik

  - name: dex
    chart: dex/dex
    namespace: dex
    needs: 
    - cert-manager/cert-manager
    - cert-manager/cert-manager-issuer
    - traefik/traefik
    values:
    - ../dex/values.yaml

  - name: dex-addition-resources
    chart: ../dex/addition-resources
    needs: 
    - dex/dex
    hooks:
    - events:
        - presync
      command: "sh"
      args:
      - "../dex/Set-RBACUserName.sh"

  - name: coredns-custom
    chart: ../coreDNS
    namespace: kube-system
    hooks:
      - events:
          - presync
        showlogs: true
        command: "sh"
        args: 
        - "../coreDNS/Set-IPAddress.sh"

  - name: loginapp
    chart: fydrah-stable/loginapp
    namespace: dex
    needs: 
    - cert-manager/cert-manager
    - cert-manager/cert-manager-issuer
    - traefik/traefik
    - traefik/traefik-addition-resources
    - dex/dex
    - kube-system/coredns-custom
    hooks:
    - events:
        - presync
      showlogs: true
      command: "sh"
      args: 
      - "../loginapp/Set-CACert.sh"
    values:
    - ../loginapp/values.yaml

  - name: kube-dashboard-addition-resources
    chart: ../kube-dashboard/addition-resources
    namespace: kube-dashboard
    needs:
    - traefik/traefik

  - name: kube-dashboard
    chart: kubernetes-dashboard/kubernetes-dashboard
    namespace: kube-dashboard
    needs:
    - cert-manager/cert-manager
    - cert-manager/cert-manager-issuer
    - traefik/traefik
    - traefik/traefik-addition-resources
    - dex/dex
    - dex/loginapp
    - kube-dashboard/kube-dashboard-addition-resources
    values:
    - ../kube-dashboard/values-update.yaml