apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freeipa
spec:
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: freeipa
data:
  ipa-server-install-options: |
    --domain=infra.sololab
    --realm=infra.sololab
    --ds-password=P@ssw0rd
    --admin-password=P@ssw0rd
    --no-ntp
    --unattended
    --no_hbac_allow

    --setup-dns
    --no-host-dns
    --forwarder=192.168.255.1
    --auto-reverse

    --debug
    --skip-mem-check
  ipa-ext.conf: |
    key "keySololab" {
            algorithm hmac-sha256;
            secret "j/2DR2zkVAyDHL2XjE731sMt9s6cmRhXE6niScAgHA0=";
    };
---
apiVersion: v1
kind: Pod
metadata:
  name: freeipa
  labels:
    name: freeipa
spec:
  # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html
  # https://www.freeipa.org/page/Docker#FreeIPA_server_containers
  hostname: ipa.infra.sololab
  containers:
    - name: freeipa
      image: quay.io/freeipa/freeipa-server:fedora-37-4.10.1
      # fedora-37-4.10.0 has bug when stup dirsvc
      # image: quay.io/freeipa/freeipa-server:fedora-37-4.10.0
      # image: docker.io/freeipa/freeipa-server:fedora-37-4.10.0
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "1536Mi"
          cpu: "1000m"
      # https://www.freeipa.org/page/V4/Replica_Conncheck
      # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html#container-fields
      ports:
        # https://github.com/sameersbn/docker-bind/issues/65
        - name: dns_tcp
          containerPort: 53
          hostIP: 192.168.255.31
          protocol: TCP
        - name: dns_udp
          hostIP: 192.168.255.31
          containerPort: 53
          protocol: UDP

        - name: http
          containerPort: 80
          hostIP: 192.168.255.31
          hostPort: 80
        - name: https
          containerPort: 443
          hostIP: 192.168.255.31
          hostPort: 443
        - name: https-pki
          containerPort: 8443
          hostIP: 192.168.255.31
          hostPort: 8443

        - name: ldap
          containerPort: 389
        - name: ldaps
          containerPort: 636

        - name: kerberos_tcp
          containerPort: 88
          protocol: TCP
        - name: kerberos_udp
          containerPort: 88
          protocol: UDP

        - name: kpasswd_tcp
          containerPort: 464
          protocol: TCP
        - name: kpasswd_udp
          containerPort: 464
          protocol: UDP
      env:
        # https://github.com/freeipa/freeipa-container#running-freeipa-server-container:~:text=Alternatively%2C%20the-,IPA_SERVER_IP,-environment%20variable%20via
        - name: IPA_SERVER_IP
          value: "192.168.255.31"
        - name: IPA_SERVER_HOSTNAME
          value: ipa.infra.sololab
      volumeMounts:
        # https://github.com/freeipa/freeipa-container#running-freeipa-server-container
        - name: freeipa
          mountPath: /data
        - name: ipa-server-install-options
          mountPath: /data/ipa-server-install-options
          subPath: ipa-server-install-options
        - name: ipa-ext.conf
          mountPath: /etc/named/ipa-ext.conf
          subPath: ipa-ext.conf
        # https://github.com/freeipa/freeipa-container/commit/024676573b6a59b4b361e35808f55739bd793e63  
        # - name: dshm
        #   mountPath: /dev/shm
        # - name: cgroups
        #   mountPath: /sys/fs/cgroup
        #   readOnly: true
  volumes:
    # https://manpages.debian.org/experimental/freeipa-server/ipa-server-install.1.en.html
    # https://github.com/search?p=1&q=ipa-server-install-options&type=Code
    - name: freeipa
      persistentVolumeClaim:
        claimName: freeipa
    - name: ipa-server-install-options
      configMap:
        name: freeipa
        items:
          - key: ipa-server-install-options
            path: ipa-server-install-options
    - name: ipa-ext.conf
      configMap:
        name: freeipa
        items:
          - key: ipa-ext.conf
            path: ipa-ext.conf
    # https://github.com/freeipa/freeipa-container/commit/024676573b6a59b4b361e35808f55739bd793e63  
    # - name: dshm
    #   emptyDir:
    #     medium: Memory
    #     sizeLimit: 128Mi
    # - name: cgroups
    #   hostPath:
    #     path: /sys/fs/cgroup
  dnsConfig:
    nameservers:
      - 127.0.0.1
  restartPolicy: Never