apiVersion: v1
kind: Pod
metadata:
  name: freeipa
  labels:
    name: freeipa
spec:
  # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html
  # https://www.freeipa.org/page/Docker#FreeIPA_server_containers
  hostname: infrasvc-fedora37.sololab
  containers:
    - name: freeipa
      image: docker.io/freeipa/freeipa-server:fedora-37
      env:
        - name: TZ
          value: Asia/Shanghai
        - name: IPA_SERVER_IP
          value: ""
          # value: "192.168.255.31"
        - name: IPA_SERVER_HOSTNAME
          value: infrasvc-fedora37.sololab
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
      # https://www.freeipa.org/page/V4/Replica_Conncheck
      # https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html#container-fields
      ports:
        # https://github.com/sameersbn/docker-bind/issues/65
        - name: dns_tcp
          hostIP: 192.168.255.31
          containerPort: 53
          protocol: TCP
        - name: dns_udp
          hostIP: 192.168.255.31
          containerPort: 53
          protocol: UDP

        - name: http
          containerPort: 80
          hostPort: 80
          # hostPort: 8080
        - name: https
          containerPort: 443
          hostPort: 443
          # hostPort: 8443

        - name: ldap
          containerPort: 389
        - name: ldaps
          containerPort: 636

        - name: kerberos_tcp
          containerPort: 88
          protocol: TCP
        - name: kerberos_udp
          containerPort: 88
          protocol: UDP

        - name: kpasswd_tcp
          containerPort: 464
          protocol: TCP
        - name: kpasswd_udp
          containerPort: 464
          protocol: UDP

      volumeMounts:
        # https://github.com/freeipa/freeipa-container#running-freeipa-server-container
        - name: freeipa
          mountPath: /data
  volumes:
    # - name: freeipa
    #   # https://kubernetes.io/docs/concepts/storage/volumes/#configmap
    #   configMap:
    #     name: freeipa
    #     items:
    #       - key: config.hcl
    #         path: config.hcl
    
    # https://manpages.debian.org/experimental/freeipa-server/ipa-server-install.1.en.html
    # https://github.com/search?p=1&q=ipa-server-install-options&type=Code
    - name: freeipa
      hostPath:
        path: /home/vagrant/infra/freeipa/data
        type: Directory
  restartPolicy: OnFailure